# Copyright (c) 2026-present Navinspire IA
# SPDX-License-Identifier: AGPL-3.0-only

"""First-party catalog of Navin app templates.

`templates_apps/` is a local gitignored clone cache. This module is the
versioned source of truth that the site, WebUI and future CLI can import.
"""

from __future__ import annotations

from navin.templates.apps.schema import APP_TEMPLATE_SCHEMA, AppTemplate

UNIVERSAL_AGENTS = [
    "research-agent",
    "analytics-agent",
    "document-agent",
    "knowledge-agent",
    "automation-agent",
]


def _t(
    slug: str,
    name: str,
    description: str,
    *,
    kind: str,
    category: str,
    stack: list[str],
    license: str,
    source_github: str,
    source_name: str,
    domain_agents: list[str],
    create_app_id: str | None = None,
    featured: bool = False,
    audit_status: str = "pending",
) -> AppTemplate:
    return {
        "schema": APP_TEMPLATE_SCHEMA,
        "slug": slug,
        "name": name,
        "description": description,
        "kind": kind,  # type: ignore[typeddict-item]
        "category": category,
        "stack": stack,
        "license": license,  # type: ignore[typeddict-item]
        "source_github": source_github,
        "source_name": source_name,
        "create_app_id": create_app_id,
        "featured": featured,
        "status": "source",
        "audit_status": audit_status,  # type: ignore[typeddict-item]
        "universal_agents": list(UNIVERSAL_AGENTS),
        "domain_agents": domain_agents,
    }


APP_TEMPLATES: list[AppTemplate] = [
    _t(
        "finance-ai",
        "Finance AI",
        "Budget, cashflow and forecast workspace with an AI CFO.",
        kind="business",
        category="finance",
        stack=["Next.js", "React", "Supabase", "Prisma"],
        license="MIT",
        source_github="https://github.com/cloudwhynot/ai-budget-manager",
        source_name="AI Budget Manager",
        create_app_id="fintech",
        featured=True,
        domain_agents=["cfo-agent", "cashflow-agent", "budget-agent", "expense-analyst", "forecast-agent"],
    ),
    _t(
        "hr-management",
        "HR Management",
        "HRMS for people, recruiting, onboarding and payroll assistance.",
        kind="business",
        category="hr",
        stack=["Next.js", "TypeScript", "Supabase"],
        license="MIT",
        source_github="https://github.com/HarshalLathiya/HR_Management_System",
        source_name="DayFlow HRMS",
        create_app_id="hr",
        domain_agents=["hr-copilot", "recruiting-agent", "onboarding-agent", "payroll-assistant", "performance-agent"],
    ),
    _t(
        "ecommerce",
        "E-commerce Platform",
        "Commerce engine (Medusa core MIT, exclude Enterprise Edition).",
        kind="business",
        category="commerce",
        stack=["Node.js", "TypeScript", "React"],
        license="MIT",
        source_github="https://github.com/medusajs/medusa",
        source_name="Medusa",
        create_app_id="ecommerce",
        featured=True,
        domain_agents=["ecommerce-manager", "sales-agent", "product-agent", "inventory-agent", "support-agent"],
    ),
    _t(
        "accounting",
        "Accounting / Invoicing",
        "Invoices, expenses and reporting for small finance teams.",
        kind="business",
        category="finance",
        stack=["Next.js", "TypeScript"],
        license="MIT",
        source_github="https://github.com/muhammad-fiaz/OpenBook",
        source_name="OpenBook",
        create_app_id="accounting",
        domain_agents=["accounting-agent", "invoice-agent", "expense-agent", "reconciliation-agent", "tax-reporting-assistant"],
    ),
    _t(
        "real-estate",
        "Real Estate Platform",
        "Listings, leads, matching and visit workflows.",
        kind="business",
        category="real-estate",
        stack=["React", "Next.js", "Express"],
        license="MIT",
        source_github="https://github.com/AHMAD-JX/Hozn-RealEstate-Fullstack",
        source_name="Hozn Real Estate",
        create_app_id="real-estate",
        featured=True,
        domain_agents=["real-estate-agent", "lead-qualification-agent", "property-matching-agent", "visit-scheduling-agent", "documentation-agent"],
    ),
    _t(
        "ai-workspace",
        "AI Workspace",
        "Hackable Next.js chatbot workspace (Vercel AI SDK).",
        kind="ai-product",
        category="chat",
        stack=["Next.js", "React", "PostgreSQL"],
        license="Apache-2.0",
        source_github="https://github.com/vercel/chatbot",
        source_name="Vercel Chatbot",
        create_app_id="assistant",
        featured=True,
        domain_agents=["general-assistant", "research-agent", "browser-agent", "document-agent", "coding-agent"],
    ),
    _t(
        "crm",
        "CRM / Sales",
        "Contacts, companies, leads, deals and pipeline with sales agents.",
        kind="business",
        category="crm",
        stack=["React", "Supabase", "shadcn"],
        license="MIT",
        source_github="https://github.com/marmelab/atomic-crm",
        source_name="Atomic CRM",
        create_app_id="crm",
        featured=True,
        audit_status="in_review",
        domain_agents=["sales-agent", "lead-qualification-agent", "follow-up-agent", "account-manager-agent", "sales-forecast-agent"],
    ),
    _t(
        "project-management",
        "Project Management",
        "PERN project board, tasks and reporting.",
        kind="business",
        category="operations",
        stack=["React", "Node", "Express", "PostgreSQL"],
        license="MIT",
        source_github="https://github.com/elyse502/project-management",
        source_name="Project Management PERN",
        create_app_id="project",
        domain_agents=["project-manager-agent", "planning-agent", "task-agent", "risk-agent", "meeting-reporting-agent"],
    ),
    _t(
        "helpdesk",
        "Helpdesk",
        "Tickets, knowledge and SLA for customer support.",
        kind="business",
        category="support",
        stack=["React", "Django", "Python"],
        license="MIT",
        source_github="https://github.com/imaradesk/imaradesk-os",
        source_name="ImaraDesk",
        create_app_id="helpdesk",
        domain_agents=["support-agent", "ticket-triage-agent", "knowledge-agent", "sla-agent", "customer-success-agent"],
    ),
    _t(
        "analytics",
        "Analytics / BI",
        "Privacy-friendly product analytics (Umami).",
        kind="business",
        category="analytics",
        stack=["Next.js", "React", "TypeScript"],
        license="MIT",
        source_github="https://github.com/umami-software/umami",
        source_name="Umami",
        create_app_id="analytics",
        featured=True,
        domain_agents=["data-analyst-agent", "kpi-agent", "report-agent", "anomaly-agent", "executive-insights-agent"],
    ),
    _t(
        "ai-agent-builder",
        "AI Agent Builder",
        "GUI to spawn, tool and run autonomous agents (replaces Langflow).",
        kind="ai-product",
        category="agents",
        stack=["Python", "Next.js"],
        license="MIT",
        source_github="https://github.com/TransformerOptimus/SuperAGI",
        source_name="SuperAGI",
        create_app_id="agent",
        featured=True,
        domain_agents=["agent-creator", "tool-builder-agent", "workflow-agent", "agent-evaluator", "agent-debugger"],
    ),
    _t(
        "rag-platform",
        "RAG / Knowledge Platform",
        "Document ingestion, retrieval and grounded Q&A.",
        kind="ai-product",
        category="rag",
        stack=["Python", "Web frontend"],
        license="Apache-2.0",
        source_github="https://github.com/infiniflow/ragflow",
        source_name="RAGFlow",
        create_app_id="rag",
        featured=True,
        domain_agents=["knowledge-agent", "document-ingestion-agent", "research-agent", "qa-agent", "knowledge-curator"],
    ),
    _t(
        "ai-data-analyst",
        "AI Data Analyst",
        "Text-to-SQL, charts and reports over business data.",
        kind="ai-product",
        category="analytics",
        stack=["Python", "Web UI"],
        license="MIT",
        featured=True,
        source_github="https://github.com/eosphoros-ai/DB-GPT",
        source_name="DB-GPT",
        create_app_id="dashboard",
        domain_agents=["sql-agent", "data-analyst-agent", "visualization-agent", "dashboard-agent", "report-generator"],
    ),
    _t(
        "ai-automation",
        "AI Automation",
        "Data and AI workflows with a React UI.",
        kind="ai-product",
        category="automation",
        stack=["Python", "React"],
        license="Apache-2.0",
        featured=True,
        source_github="https://github.com/mage-ai/mage-ai",
        source_name="Mage AI",
        create_app_id="agent",
        domain_agents=["automation-agent", "integration-agent", "workflow-builder", "failure-recovery-agent", "operations-agent"],
    ),
    _t(
        "clinic-management",
        "Clinic / Medical Practice",
        "Appointments and practice admin for clinics.",
        kind="business",
        category="healthcare",
        stack=["Next.js", "React"],
        license="MIT",
        source_github="https://github.com/SoulHiro/doutor-agenda",
        source_name="Doutor Agenda",
        create_app_id="healthcare",
        domain_agents=["medical-admin-agent", "appointment-agent", "patient-documentation-agent", "billing-agent", "practice-analytics-agent"],
    ),
    _t(
        "pharmacy-management",
        "Pharmacy",
        "Inventory, expiry and pharmacy sales operations.",
        kind="business",
        category="healthcare",
        stack=["React", "Node", "Express", "MongoDB"],
        license="MIT",
        source_github="https://github.com/GirumY4/pharma-net-platform",
        source_name="Pharma-Net",
        domain_agents=["pharmacy-assistant", "inventory-agent", "procurement-agent", "expiry-monitoring-agent", "sales-analytics-agent"],
    ),
    _t(
        "booking",
        "Booking SaaS",
        "Availability, reminders and appointment booking.",
        kind="business",
        category="booking",
        stack=["React", "Vite", "Express", "PostgreSQL"],
        license="MIT",
        source_github="https://github.com/bhanu87777/BookIt-Appointment-Booking-System",
        source_name="BookIt",
        create_app_id="booking",
        domain_agents=["scheduling-agent", "availability-agent", "reminder-agent", "customer-assistant", "revenue-optimization-agent"],
    ),
    _t(
        "lms",
        "LMS / E-learning",
        "Courses, quizzes and learner progress.",
        kind="business",
        category="education",
        stack=["React", "Node.js", "TypeScript"],
        license="MIT",
        source_github="https://github.com/Selleo/mentingo",
        source_name="Mentingo",
        create_app_id="lms",
        domain_agents=["ai-tutor", "course-creator-agent", "quiz-generator", "student-progress-agent", "teacher-assistant"],
    ),
    _t(
        "inventory",
        "Inventory / Warehouse",
        "Stock, warehouses, orders and shipping hooks.",
        kind="business",
        category="operations",
        stack=["Next.js", "React", "Prisma"],
        license="MIT",
        source_github="https://github.com/arnobt78/Warehouse-Stock-Inventory-Management-System--NextJS-FullStack",
        source_name="Stock Inventory Management",
        create_app_id="inventory",
        domain_agents=["inventory-agent", "procurement-agent", "demand-forecast-agent", "warehouse-agent", "logistics-agent"],
    ),
    _t(
        "stock-pilot",
        "Commercial / Sales & Purchases",
        "Sales, purchases, suppliers, customers, POS, invoices, stock, margins and reporting.",
        kind="business",
        category="commerce",
        stack=["React", "Node.js", "PostgreSQL"],
        license="MIT",
        source_github="https://github.com/zacktam12/StockPilot",
        source_name="StockPilot",
        create_app_id="inventory",
        domain_agents=["sales-agent", "purchase-agent", "supplier-agent", "invoice-agent", "stock-agent"],
    ),
    _t(
        "sales-inventory",
        "Sales / Purchase Inventory",
        "Products, vendors, purchases, sales, history and stock levels.",
        kind="business",
        category="operations",
        stack=["React", "TypeScript", "Node.js", "Express", "MongoDB"],
        license="MIT",
        source_github="https://github.com/mhShohan/inventory-management-system",
        source_name="Inventory Management System",
        create_app_id="inventory",
        domain_agents=["product-agent", "vendor-agent", "purchase-agent", "sales-agent", "stock-agent"],
    ),
    _t(
        "purchase-orders",
        "Stock / Purchase Orders",
        "Suppliers, purchase orders, sales, stock, users and roles.",
        kind="business",
        category="operations",
        stack=["React", "Node.js", "Express", "TypeScript", "MongoDB"],
        license="MIT",
        source_github="https://github.com/nshakib/inventory-management-system-backend",
        source_name="Inventory Management System Backend",
        create_app_id="inventory",
        domain_agents=["supplier-agent", "purchase-order-agent", "sales-agent", "stock-agent", "roles-agent"],
    ),
    _t(
        "restaurant-pos",
        "Restaurant / POS",
        "Point of sale and cafe operations.",
        kind="business",
        category="hospitality",
        stack=["Next.js", "React"],
        license="MIT",
        source_github="https://github.com/FreeOpenSourcePOS/FloCafe",
        source_name="FloCafe",
        create_app_id="pos",
        domain_agents=["restaurant-manager-agent", "ordering-agent", "inventory-agent", "reservation-agent", "kitchen-operations-agent"],
    ),
    _t(
        "hotel-management",
        "Hotel Management",
        "Rooms, bookings and hotel admin.",
        kind="business",
        category="hospitality",
        stack=["Next.js", "React", "Express", "MongoDB"],
        license="Apache-2.0",
        source_github="https://github.com/SamiurRahmanMukul/Hotel-Room-Booking-System",
        source_name="Hotel Room Booking System",
        create_app_id="booking",
        domain_agents=["front-desk-agent", "reservation-agent", "housekeeping-agent", "guest-assistant", "revenue-agent"],
    ),
    _t(
        "ats-recruitment",
        "ATS / Recruitment",
        "Jobs, candidates and hiring pipeline.",
        kind="business",
        category="hr",
        stack=["Next.js", "React"],
        license="MIT",
        source_github="https://github.com/Vytral/harly",
        source_name="Harly ATS",
        create_app_id="recruitment",
        domain_agents=["recruiting-agent", "cv-screening-agent", "interview-agent", "pipeline-agent", "offer-agent"],
    ),
    _t(
        "school-management",
        "School Management",
        "School ERP for classes, staff and students.",
        kind="business",
        category="education",
        stack=["Next.js", "React"],
        license="MIT",
        source_github="https://github.com/biprodas/school-erp",
        source_name="School ERP",
        create_app_id="lms",
        domain_agents=["school-admin-agent", "attendance-agent", "timetable-agent", "parent-assistant", "academic-report-agent"],
    ),
    _t(
        "dental-clinic",
        "Dental Clinic",
        "Agenda, odontogram, treatment plans and billing.",
        kind="business",
        category="healthcare",
        stack=["React", "Vite", "TypeScript"],
        license="MIT",
        source_github="https://github.com/clawnify/open-dentist",
        source_name="Open Dentist",
        create_app_id="healthcare",
        domain_agents=["dental-admin-agent", "appointment-agent", "charting-agent", "billing-agent", "follow-up-agent"],
    ),
    _t(
        "veterinary-clinic",
        "Veterinary Clinic",
        "Vet clinic pages and appointment booking.",
        kind="business",
        category="healthcare",
        stack=["Next.js", "React"],
        license="MIT",
        source_github="https://github.com/pjborowiecki/ARKA-Veterinary-Clinic-Page-and-Appointment-Booking-System",
        source_name="ARKA Veterinary Clinic",
        create_app_id="healthcare",
        domain_agents=["vet-admin-agent", "appointment-agent", "pet-records-agent", "reminder-agent", "billing-agent"],
    ),
    _t(
        "insurance",
        "Insurance",
        "Policies, coverage and agency workflows.",
        kind="business",
        category="finance",
        stack=["Next.js", "React"],
        license="MIT",
        source_github="https://github.com/aaln/open-coverage",
        source_name="Open Coverage",
        create_app_id="fintech",
        domain_agents=["policy-agent", "claims-assistant", "renewal-agent", "risk-agent", "client-advisor"],
    ),
    _t(
        "fleet-management",
        "Fleet Management",
        "Vehicles, drivers, loads and compliance.",
        kind="business",
        category="logistics",
        stack=["Next.js", "Prisma", "PostgreSQL"],
        license="MIT",
        source_github="https://github.com/DigitalHerencia/FleetFusion",
        source_name="FleetFusion",
        create_app_id="logistics",
        domain_agents=["dispatch-agent", "driver-agent", "maintenance-agent", "compliance-agent", "route-agent"],
    ),
    _t(
        "garage",
        "Garage / Workshop",
        "Job cards, vehicles, invoices and workshop roles.",
        kind="business",
        category="operations",
        stack=["Next.js", "PostgreSQL", "Prisma"],
        license="MIT",
        source_github="https://github.com/PhutiCee/panel-beating-management-system",
        source_name="Panel Beating Management",
        domain_agents=["workshop-manager-agent", "job-card-agent", "parts-agent", "invoice-agent", "customer-agent"],
    ),
    _t(
        "delivery",
        "Delivery / Courier",
        "Customer, restaurant, driver and admin delivery apps.",
        kind="business",
        category="logistics",
        stack=["Next.js", "Express", "React"],
        license="MIT",
        source_github="https://github.com/roaziy/ubdelivery",
        source_name="UBDelivery",
        create_app_id="delivery",
        domain_agents=["dispatch-agent", "driver-agent", "order-agent", "eta-agent", "support-agent"],
    ),
    _t(
        "social-network",
        "Social Network",
        "Posts, follows and realtime social feed.",
        kind="business",
        category="social",
        stack=["Next.js", "Supabase"],
        license="MIT",
        source_github="https://github.com/maazajaz/socialens",
        source_name="SociaLens",
        create_app_id="social",
        domain_agents=["moderation-agent", "feed-agent", "community-agent", "growth-agent", "safety-agent"],
    ),
    _t(
        "email-marketing",
        "Email Marketing",
        "Campaigns, audience and SES-backed sending.",
        kind="business",
        category="marketing",
        stack=["Next.js", "Supabase", "AWS SES"],
        license="MIT",
        source_github="https://github.com/createdbymax/Loopletter-Open-source-email-marketing-platform",
        source_name="Loopletter",
        create_app_id="emailing",
        domain_agents=["campaign-agent", "audience-agent", "copy-agent", "deliverability-agent", "analytics-agent"],
    ),
    _t(
        "cms",
        "CMS",
        "Headless / Next.js-native CMS (Payload).",
        kind="business",
        category="content",
        stack=["Next.js", "React", "TypeScript"],
        license="MIT",
        source_github="https://github.com/payloadcms/payload",
        source_name="Payload CMS",
        create_app_id="website",
        featured=True,
        domain_agents=["content-agent", "seo-agent", "media-agent", "publisher-agent", "localization-agent"],
    ),
    _t(
        "saas-starter",
        "SaaS Starter",
        "Auth, teams, Stripe and dashboard starter.",
        kind="business",
        category="saas",
        stack=["Next.js", "Postgres", "Stripe", "shadcn"],
        license="MIT",
        source_github="https://github.com/nextjs/saas-starter",
        source_name="Next.js SaaS Starter",
        create_app_id="saas",
        featured=True,
        domain_agents=["onboarding-agent", "billing-agent", "admin-agent", "support-agent", "growth-agent"],
    ),
    _t(
        "restaurant-delivery",
        "Restaurant Delivery",
        "Food ordering storefront plus admin (Payload).",
        kind="business",
        category="hospitality",
        stack=["Next.js", "Payload CMS", "MongoDB"],
        license="MIT",
        source_github="https://github.com/Shatlyk1011/food-delivery-app",
        source_name="Ashpez Food Delivery",
        create_app_id="restaurant",
        domain_agents=["ordering-agent", "menu-agent", "delivery-agent", "promo-agent", "support-agent"],
    ),
    _t(
        "salon-spa",
        "Salon / Spa",
        "Multi-salon booking, services and reviews.",
        kind="business",
        category="booking",
        stack=["Next.js", "MongoDB", "TypeScript"],
        license="MIT",
        source_github="https://github.com/harshanacz/salonbookinglk_platform",
        source_name="SalonBooking.lk",
        create_app_id="booking",
        domain_agents=["booking-agent", "stylist-agent", "reminder-agent", "review-agent", "inventory-agent"],
    ),
    _t(
        "event-management",
        "Event Management",
        "Events, tickets and Stripe checkout.",
        kind="business",
        category="events",
        stack=["Next.js", "MongoDB", "Clerk", "Stripe"],
        license="MIT",
        source_github="https://github.com/sanidhyy/evently",
        source_name="Evently",
        domain_agents=["event-agent", "ticketing-agent", "promotion-agent", "attendee-agent", "report-agent"],
    ),
    _t(
        "legal",
        "Legal Case Management",
        "Cases, hearings, parties and e-filing roles.",
        kind="business",
        category="legal",
        stack=["Next.js", "Fastify", "Prisma", "PostgreSQL"],
        license="MIT",
        source_github="https://github.com/tpt-solutions/tpt-court",
        source_name="TPT Court",
        create_app_id="legal",
        domain_agents=["case-agent", "deadline-agent", "document-agent", "hearing-agent", "client-update-agent"],
    ),
    _t(
        "travel-agency",
        "Travel Agency",
        "AI-assisted travel ops and lead handling.",
        kind="business",
        category="travel",
        stack=["Next.js", "Firebase", "Vercel AI SDK"],
        license="MIT",
        source_github="https://github.com/Minato95-ayu/travel-os",
        source_name="TravelOS",
        domain_agents=["travel-advisor", "itinerary-agent", "quote-agent", "booking-agent", "follow-up-agent"],
    ),
    _t(
        "manufacturing",
        "Manufacturing / MRP",
        "BOM, production runs and factory inventory.",
        kind="business",
        category="manufacturing",
        stack=["FastAPI", "Next.js", "PostgreSQL"],
        license="MIT",
        source_github="https://github.com/bryanadamg/terras-erp",
        source_name="Teras ERP",
        create_app_id="manufacturing",
        domain_agents=["mrp-agent", "production-agent", "quality-agent", "procurement-agent", "inventory-agent"],
    ),
    _t(
        "ai-chat",
        "AI Chatbot",
        "Multi-provider chat, agents, MCP and artifacts. The main chatbot studio.",
        kind="ai-product",
        category="chat",
        stack=["React", "Node", "MongoDB", "MCP"],
        license="MIT",
        source_github="https://github.com/danny-avila/LibreChat",
        source_name="LibreChat",
        create_app_id="chatbot",
        featured=True,
        domain_agents=["chat-agent", "mcp-agent", "artifact-agent", "preset-agent", "moderation-agent"],
    ),
    _t(
        "ai-rag-chat",
        "RAG Workspace",
        "Chat with documents, agents and a no-code builder.",
        kind="ai-product",
        category="rag",
        stack=["React", "Node", "RAG"],
        license="MIT",
        source_github="https://github.com/Mintplex-Labs/anything-llm",
        source_name="AnythingLLM",
        create_app_id="rag",
        featured=True,
        domain_agents=["workspace-agent", "ingestion-agent", "rag-agent", "agent-builder", "connector-agent"],
    ),
    _t(
        "ai-search",
        "AI Search",
        "Perplexity-style search with cited sources.",
        kind="ai-product",
        category="search",
        stack=["Next.js", "TypeScript"],
        license="MIT",
        source_github="https://github.com/ItzCrazyKns/Perplexica",
        source_name="Perplexica",
        create_app_id="research",
        featured=True,
        domain_agents=["search-agent", "citation-agent", "follow-up-agent", "brief-agent", "source-ranker"],
    ),
    _t(
        "ai-chat-ui",
        "ChatGPT-style UI",
        "Lightweight one-click chat UI for many models.",
        kind="ai-product",
        category="chat",
        stack=["Next.js", "React"],
        license="MIT",
        source_github="https://github.com/ChatGPTNextWeb/NextChat",
        source_name="NextChat",
        create_app_id="chatbot",
        featured=True,
        domain_agents=["chat-agent", "prompt-agent", "model-router", "export-agent", "theme-agent"],
    ),
    _t(
        "document-rag",
        "Document RAG",
        "QA over files with collections and citations.",
        kind="ai-product",
        category="rag",
        stack=["Python", "Gradio", "RAG"],
        license="Apache-2.0",
        source_github="https://github.com/Cinnamon/kotaemon",
        source_name="Kotaemon",
        create_app_id="rag",
        featured=True,
        domain_agents=["ingestion-agent", "qa-agent", "citation-agent", "collection-agent", "share-agent"],
    ),
    _t(
        "coding-agent",
        "Coding Agent",
        "Software agent with UI over code, terminal and files.",
        kind="ai-product",
        category="agents",
        stack=["Python", "React"],
        license="MIT",
        source_github="https://github.com/All-Hands-AI/OpenHands",
        source_name="OpenHands",
        create_app_id="agent",
        featured=True,
        domain_agents=["coding-agent", "review-agent", "test-agent", "terminal-agent", "pr-agent"],
    ),
    _t(
        "browser-agent",
        "Browser Agent",
        "Agent that drives a real browser.",
        kind="ai-product",
        category="agents",
        stack=["Python", "Gradio"],
        license="MIT",
        source_github="https://github.com/browser-use/web-ui",
        source_name="Browser Use WebUI",
        create_app_id="scraping",
        featured=True,
        domain_agents=["browser-agent", "form-agent", "extract-agent", "watch-agent", "report-agent"],
    ),
    _t(
        "social-media-ai",
        "Social Media AI",
        "AI content plus scheduling for YouTube and TikTok.",
        kind="ai-product",
        category="social",
        stack=["Next.js", "Prisma", "PostgreSQL"],
        license="MIT",
        source_github="https://github.com/Anil-matcha/Free-AI-Social-Media-Scheduler",
        source_name="Free AI Social Media Scheduler",
        create_app_id="social",
        domain_agents=["copy-agent", "schedule-agent", "publish-agent", "analytics-agent", "repurpose-agent"],
    ),
]


def list_app_templates(
    *,
    kind: str | None = None,
    featured_only: bool = False,
) -> list[AppTemplate]:
    rows = APP_TEMPLATES
    if kind:
        rows = [row for row in rows if row["kind"] == kind]
    if featured_only:
        rows = [row for row in rows if row["featured"]]
    return list(rows)


def get_app_template(slug: str) -> AppTemplate | None:
    key = (slug or "").strip()
    for row in APP_TEMPLATES:
        if row["slug"] == key:
            return row
    return None


def template_slug_for_create_app(create_app_id: str) -> str | None:
    """Best featured (else first) template linked to a /create app id."""
    matches = [row for row in APP_TEMPLATES if row["create_app_id"] == create_app_id]
    if not matches:
        return None
    featured = [row for row in matches if row["featured"]]
    return (featured or matches)[0]["slug"]


def is_publishable(row: AppTemplate) -> bool:
    """AWS upload is allowed only after a passed audit and a Navin-normalized package."""
    return row["audit_status"] == "passed" and row["status"] == "normalized"
