import type { AppTemplateSummary } from "@/lib/types";

const UNIVERSAL = [
  "research-agent",
  "analytics-agent",
  "document-agent",
  "knowledge-agent",
  "automation-agent",
];

function card(
  // Every field this function fills in itself is omitted here and offered back
  // as optional. featured has to be in that list like audit_status: omitting it
  // is what makes the default below reachable, and intersecting a required
  // property with an optional one leaves it required.
  row: Omit<
    AppTemplateSummary,
    | "status"
    | "audit_status"
    | "installed"
    | "local_cache"
    | "can_publish"
    | "aws_key"
    | "universal_agents"
    | "featured"
  > & {
    featured?: boolean;
    audit_status?: AppTemplateSummary["audit_status"];
  },
): AppTemplateSummary {
  const { audit_status, featured, ...rest } = row;
  return {
    status: "source",
    audit_status: audit_status ?? "pending",
    installed: false,
    local_cache: false,
    can_publish: false,
    aws_key: `templates/v1/${rest.slug}.tar.gz`,
    aws_url: `https://navinagent.s3.eu-north-1.amazonaws.com/templates/v1/${rest.slug}.tar.gz`,
    universal_agents: UNIVERSAL,
    featured: featured ?? false,
    ...rest,
  };
}

/** Mirror of navin/templates/apps/catalog.py. Shown if the gateway catalog is empty. */
export const APP_TEMPLATES_FALLBACK: AppTemplateSummary[] = [
  card({
    slug: "finance-ai",
    name: "Finance AI",
    description: "Budget, cashflow and forecast workspace with an AI CFO.",
    kind: "business",
    category: "finance",
    stack: ["Next.js", "React", "Supabase", "Prisma"],
    license: "MIT",
    source_github: "https://github.com/cloudwhynot/ai-budget-manager",
    source_name: "AI Budget Manager",
    create_app_id: "fintech",
    featured: true,
    domain_agents: ["cfo-agent", "cashflow-agent", "budget-agent", "expense-analyst", "forecast-agent"],
  }),
  card({
    slug: "hr-management",
    name: "HR Management",
    description: "HRMS for people, recruiting, onboarding and payroll assistance.",
    kind: "business",
    category: "hr",
    stack: ["Next.js", "TypeScript", "Supabase"],
    license: "MIT",
    source_github: "https://github.com/HarshalLathiya/HR_Management_System",
    source_name: "DayFlow HRMS",
    create_app_id: "hr",
    domain_agents: ["hr-copilot", "recruiting-agent", "onboarding-agent", "payroll-assistant", "performance-agent"],
  }),
  card({
    slug: "ecommerce",
    name: "E-commerce Platform",
    description: "Commerce engine (Medusa core MIT, exclude Enterprise Edition).",
    kind: "business",
    category: "commerce",
    stack: ["Node.js", "TypeScript", "React"],
    license: "MIT",
    source_github: "https://github.com/medusajs/medusa",
    source_name: "Medusa",
    create_app_id: "ecommerce",
    featured: true,
    domain_agents: ["ecommerce-manager", "sales-agent", "product-agent", "inventory-agent", "support-agent"],
  }),
  card({
    slug: "accounting",
    name: "Accounting / Invoicing",
    description: "Invoices, expenses and reporting for small finance teams.",
    kind: "business",
    category: "finance",
    stack: ["Next.js", "TypeScript"],
    license: "MIT",
    source_github: "https://github.com/muhammad-fiaz/OpenBook",
    source_name: "OpenBook",
    create_app_id: "accounting",
    domain_agents: ["accounting-agent", "invoice-agent", "expense-agent", "reconciliation-agent", "tax-reporting-assistant"],
  }),
  card({
    slug: "real-estate",
    name: "Real Estate Platform",
    description: "Listings, leads, matching and visit workflows.",
    kind: "business",
    category: "real-estate",
    stack: ["React", "Next.js", "Express"],
    license: "MIT",
    source_github: "https://github.com/AHMAD-JX/Hozn-RealEstate-Fullstack",
    source_name: "Hozn Real Estate",
    create_app_id: "real-estate",
    featured: true,
    domain_agents: ["real-estate-agent", "lead-qualification-agent", "property-matching-agent", "visit-scheduling-agent", "documentation-agent"],
  }),
  card({
    slug: "ai-workspace",
    name: "AI Workspace",
    description: "Hackable Next.js chatbot workspace (Vercel AI SDK).",
    kind: "ai-product",
    category: "chat",
    stack: ["Next.js", "React", "PostgreSQL"],
    license: "Apache-2.0",
    source_github: "https://github.com/vercel/chatbot",
    source_name: "Vercel Chatbot",
    create_app_id: "assistant",
    featured: true,
    domain_agents: ["general-assistant", "research-agent", "browser-agent", "document-agent", "coding-agent"],
  }),
  card({
    slug: "crm",
    name: "CRM / Sales",
    description: "Contacts, companies, leads, deals and pipeline with sales agents.",
    kind: "business",
    category: "crm",
    stack: ["React", "Supabase", "shadcn"],
    license: "MIT",
    source_github: "https://github.com/marmelab/atomic-crm",
    source_name: "Atomic CRM",
    create_app_id: "crm",
    featured: true,
    audit_status: "in_review",
    domain_agents: ["sales-agent", "lead-qualification-agent", "follow-up-agent", "account-manager-agent", "sales-forecast-agent"],
  }),
  card({
    slug: "project-management",
    name: "Project Management",
    description: "PERN project board, tasks and reporting.",
    kind: "business",
    category: "operations",
    stack: ["React", "Node", "Express", "PostgreSQL"],
    license: "MIT",
    source_github: "https://github.com/elyse502/project-management",
    source_name: "Project Management PERN",
    create_app_id: "project",
    domain_agents: ["project-manager-agent", "planning-agent", "task-agent", "risk-agent", "meeting-reporting-agent"],
  }),
  card({
    slug: "helpdesk",
    name: "Helpdesk",
    description: "Tickets, knowledge and SLA for customer support.",
    kind: "business",
    category: "support",
    stack: ["React", "Django", "Python"],
    license: "MIT",
    source_github: "https://github.com/imaradesk/imaradesk-os",
    source_name: "ImaraDesk",
    create_app_id: "helpdesk",
    domain_agents: ["support-agent", "ticket-triage-agent", "knowledge-agent", "sla-agent", "customer-success-agent"],
  }),
  card({
    slug: "analytics",
    name: "Analytics / BI",
    description: "Privacy-friendly product analytics (Umami).",
    kind: "business",
    category: "analytics",
    stack: ["Next.js", "React", "TypeScript"],
    license: "MIT",
    source_github: "https://github.com/umami-software/umami",
    source_name: "Umami",
    create_app_id: "analytics",
    featured: true,
    domain_agents: ["data-analyst-agent", "kpi-agent", "report-agent", "anomaly-agent", "executive-insights-agent"],
  }),
  card({
    slug: "ai-agent-builder",
    name: "AI Agent Builder",
    description: "GUI to spawn, tool and run autonomous agents (replaces Langflow).",
    kind: "ai-product",
    category: "agents",
    stack: ["Python", "Next.js"],
    license: "MIT",
    source_github: "https://github.com/TransformerOptimus/SuperAGI",
    source_name: "SuperAGI",
    create_app_id: "agent",
    featured: true,
    domain_agents: ["agent-creator", "tool-builder-agent", "workflow-agent", "agent-evaluator", "agent-debugger"],
  }),
  card({
    slug: "rag-platform",
    name: "RAG / Knowledge Platform",
    description: "Document ingestion, retrieval and grounded Q&A.",
    kind: "ai-product",
    category: "rag",
    stack: ["Python", "Web frontend"],
    license: "Apache-2.0",
    source_github: "https://github.com/infiniflow/ragflow",
    source_name: "RAGFlow",
    create_app_id: "rag",
    featured: true,
    domain_agents: ["knowledge-agent", "document-ingestion-agent", "research-agent", "qa-agent", "knowledge-curator"],
  }),
  card({
    slug: "ai-data-analyst",
    name: "AI Data Analyst",
    description: "Text-to-SQL, charts and reports over business data.",
    kind: "ai-product",
    category: "analytics",
    stack: ["Python", "Web UI"],
    license: "MIT",
    source_github: "https://github.com/eosphoros-ai/DB-GPT",
    source_name: "DB-GPT",
    create_app_id: "dashboard",
    featured: true,
    domain_agents: ["sql-agent", "data-analyst-agent", "visualization-agent", "dashboard-agent", "report-generator"],
  }),
  card({
    slug: "ai-automation",
    name: "AI Automation",
    description: "Data and AI workflows with a React UI.",
    kind: "ai-product",
    category: "automation",
    stack: ["Python", "React"],
    license: "Apache-2.0",
    source_github: "https://github.com/mage-ai/mage-ai",
    source_name: "Mage AI",
    create_app_id: "agent",
    featured: true,
    domain_agents: ["automation-agent", "integration-agent", "workflow-builder", "failure-recovery-agent", "operations-agent"],
  }),
  card({
    slug: "clinic-management",
    name: "Clinic / Medical Practice",
    description: "Appointments and practice admin for clinics.",
    kind: "business",
    category: "healthcare",
    stack: ["Next.js", "React"],
    license: "MIT",
    source_github: "https://github.com/SoulHiro/doutor-agenda",
    source_name: "Doutor Agenda",
    create_app_id: "healthcare",
    domain_agents: ["medical-admin-agent", "appointment-agent", "patient-documentation-agent", "billing-agent", "practice-analytics-agent"],
  }),
  card({
    slug: "pharmacy-management",
    name: "Pharmacy",
    description: "Inventory, expiry and pharmacy sales operations.",
    kind: "business",
    category: "healthcare",
    stack: ["React", "Node", "Express", "MongoDB"],
    license: "MIT",
    source_github: "https://github.com/GirumY4/pharma-net-platform",
    source_name: "Pharma-Net",
    create_app_id: null,
    domain_agents: ["pharmacy-assistant", "inventory-agent", "procurement-agent", "expiry-monitoring-agent", "sales-analytics-agent"],
  }),
  card({
    slug: "booking",
    name: "Booking SaaS",
    description: "Availability, reminders and appointment booking.",
    kind: "business",
    category: "booking",
    stack: ["React", "Vite", "Express", "PostgreSQL"],
    license: "MIT",
    source_github: "https://github.com/bhanu87777/BookIt-Appointment-Booking-System",
    source_name: "BookIt",
    create_app_id: "booking",
    domain_agents: ["scheduling-agent", "availability-agent", "reminder-agent", "customer-assistant", "revenue-optimization-agent"],
  }),
  card({
    slug: "lms",
    name: "LMS / E-learning",
    description: "Courses, quizzes and learner progress.",
    kind: "business",
    category: "education",
    stack: ["React", "Node.js", "TypeScript"],
    license: "MIT",
    source_github: "https://github.com/Selleo/mentingo",
    source_name: "Mentingo",
    create_app_id: "lms",
    domain_agents: ["ai-tutor", "course-creator-agent", "quiz-generator", "student-progress-agent", "teacher-assistant"],
  }),
  card({
    slug: "inventory",
    name: "Inventory / Warehouse",
    description: "Stock, warehouses, orders and shipping hooks.",
    kind: "business",
    category: "operations",
    stack: ["Next.js", "React", "Prisma"],
    license: "MIT",
    source_github: "https://github.com/arnobt78/Warehouse-Stock-Inventory-Management-System--NextJS-FullStack",
    source_name: "Stock Inventory Management",
    create_app_id: "inventory",
    domain_agents: ["inventory-agent", "procurement-agent", "demand-forecast-agent", "warehouse-agent", "logistics-agent"],
  }),
  card({
    slug: "stock-pilot",
    name: "Commercial / Sales & Purchases",
    description: "Sales, purchases, suppliers, customers, POS, invoices, stock, margins and reporting.",
    kind: "business",
    category: "commerce",
    stack: ["React", "Node.js", "PostgreSQL"],
    license: "MIT",
    source_github: "https://github.com/zacktam12/StockPilot",
    source_name: "StockPilot",
    create_app_id: "inventory",
    domain_agents: ["sales-agent", "purchase-agent", "supplier-agent", "invoice-agent", "stock-agent"],
  }),
  card({
    slug: "sales-inventory",
    name: "Sales / Purchase Inventory",
    description: "Products, vendors, purchases, sales, history and stock levels.",
    kind: "business",
    category: "operations",
    stack: ["React", "TypeScript", "Node.js", "Express", "MongoDB"],
    license: "MIT",
    source_github: "https://github.com/mhShohan/inventory-management-system",
    source_name: "Inventory Management System",
    create_app_id: "inventory",
    domain_agents: ["product-agent", "vendor-agent", "purchase-agent", "sales-agent", "stock-agent"],
  }),
  card({
    slug: "purchase-orders",
    name: "Stock / Purchase Orders",
    description: "Suppliers, purchase orders, sales, stock, users and roles.",
    kind: "business",
    category: "operations",
    stack: ["React", "Node.js", "Express", "TypeScript", "MongoDB"],
    license: "MIT",
    source_github: "https://github.com/nshakib/inventory-management-system-backend",
    source_name: "Inventory Management System Backend",
    create_app_id: "inventory",
    domain_agents: ["supplier-agent", "purchase-order-agent", "sales-agent", "stock-agent", "roles-agent"],
  }),
  card({
    slug: "restaurant-pos",
    name: "Restaurant / POS",
    description: "Point of sale and cafe operations.",
    kind: "business",
    category: "hospitality",
    stack: ["Next.js", "React"],
    license: "MIT",
    source_github: "https://github.com/FreeOpenSourcePOS/FloCafe",
    source_name: "FloCafe",
    create_app_id: "pos",
    domain_agents: ["restaurant-manager-agent", "ordering-agent", "inventory-agent", "reservation-agent", "kitchen-operations-agent"],
  }),
  card({
    slug: "hotel-management",
    name: "Hotel Management",
    description: "Rooms, bookings and hotel admin.",
    kind: "business",
    category: "hospitality",
    stack: ["Next.js", "React", "Express", "MongoDB"],
    license: "Apache-2.0",
    source_github: "https://github.com/SamiurRahmanMukul/Hotel-Room-Booking-System",
    source_name: "Hotel Room Booking System",
    create_app_id: "booking",
    domain_agents: ["front-desk-agent", "reservation-agent", "housekeeping-agent", "guest-assistant", "revenue-agent"],
  }),
  card({
    slug: "ats-recruitment",
    name: "ATS / Recruitment",
    description: "Jobs, candidates and hiring pipeline.",
    kind: "business",
    category: "hr",
    stack: ["Next.js", "React"],
    license: "MIT",
    source_github: "https://github.com/Vytral/harly",
    source_name: "Harly ATS",
    create_app_id: "recruitment",
    domain_agents: ["recruiting-agent", "cv-screening-agent", "interview-agent", "pipeline-agent", "offer-agent"],
  }),
  card({
    slug: "school-management",
    name: "School Management",
    description: "School ERP for classes, staff and students.",
    kind: "business",
    category: "education",
    stack: ["Next.js", "React"],
    license: "MIT",
    source_github: "https://github.com/biprodas/school-erp",
    source_name: "School ERP",
    create_app_id: "lms",
    domain_agents: ["school-admin-agent", "attendance-agent", "timetable-agent", "parent-assistant", "academic-report-agent"],
  }),
  card({
    slug: "dental-clinic",
    name: "Dental Clinic",
    description: "Agenda, odontogram, treatment plans and billing.",
    kind: "business",
    category: "healthcare",
    stack: ["React", "Vite", "TypeScript"],
    license: "MIT",
    source_github: "https://github.com/clawnify/open-dentist",
    source_name: "Open Dentist",
    create_app_id: "healthcare",
    domain_agents: ["dental-admin-agent", "appointment-agent", "charting-agent", "billing-agent", "follow-up-agent"],
  }),
  card({
    slug: "veterinary-clinic",
    name: "Veterinary Clinic",
    description: "Vet clinic pages and appointment booking.",
    kind: "business",
    category: "healthcare",
    stack: ["Next.js", "React"],
    license: "MIT",
    source_github: "https://github.com/pjborowiecki/ARKA-Veterinary-Clinic-Page-and-Appointment-Booking-System",
    source_name: "ARKA Veterinary Clinic",
    create_app_id: "healthcare",
    domain_agents: ["vet-admin-agent", "appointment-agent", "pet-records-agent", "reminder-agent", "billing-agent"],
  }),
  card({
    slug: "insurance",
    name: "Insurance",
    description: "Policies, coverage and agency workflows.",
    kind: "business",
    category: "finance",
    stack: ["Next.js", "React"],
    license: "MIT",
    source_github: "https://github.com/aaln/open-coverage",
    source_name: "Open Coverage",
    create_app_id: "fintech",
    domain_agents: ["policy-agent", "claims-assistant", "renewal-agent", "risk-agent", "client-advisor"],
  }),
  card({
    slug: "fleet-management",
    name: "Fleet Management",
    description: "Vehicles, drivers, loads and compliance.",
    kind: "business",
    category: "logistics",
    stack: ["Next.js", "Prisma", "PostgreSQL"],
    license: "MIT",
    source_github: "https://github.com/DigitalHerencia/FleetFusion",
    source_name: "FleetFusion",
    create_app_id: "logistics",
    domain_agents: ["dispatch-agent", "driver-agent", "maintenance-agent", "compliance-agent", "route-agent"],
  }),
  card({
    slug: "garage",
    name: "Garage / Workshop",
    description: "Job cards, vehicles, invoices and workshop roles.",
    kind: "business",
    category: "operations",
    stack: ["Next.js", "PostgreSQL", "Prisma"],
    license: "MIT",
    source_github: "https://github.com/PhutiCee/panel-beating-management-system",
    source_name: "Panel Beating Management",
    create_app_id: null,
    domain_agents: ["workshop-manager-agent", "job-card-agent", "parts-agent", "invoice-agent", "customer-agent"],
  }),
  card({
    slug: "delivery",
    name: "Delivery / Courier",
    description: "Customer, restaurant, driver and admin delivery apps.",
    kind: "business",
    category: "logistics",
    stack: ["Next.js", "Express", "React"],
    license: "MIT",
    source_github: "https://github.com/roaziy/ubdelivery",
    source_name: "UBDelivery",
    create_app_id: "delivery",
    domain_agents: ["dispatch-agent", "driver-agent", "order-agent", "eta-agent", "support-agent"],
  }),
  card({
    slug: "social-network",
    name: "Social Network",
    description: "Posts, follows and realtime social feed.",
    kind: "business",
    category: "social",
    stack: ["Next.js", "Supabase"],
    license: "MIT",
    source_github: "https://github.com/maazajaz/socialens",
    source_name: "SociaLens",
    create_app_id: "social",
    domain_agents: ["moderation-agent", "feed-agent", "community-agent", "growth-agent", "safety-agent"],
  }),
  card({
    slug: "email-marketing",
    name: "Email Marketing",
    description: "Campaigns, audience and SES-backed sending.",
    kind: "business",
    category: "marketing",
    stack: ["Next.js", "Supabase", "AWS SES"],
    license: "MIT",
    source_github: "https://github.com/createdbymax/Loopletter-Open-source-email-marketing-platform",
    source_name: "Loopletter",
    create_app_id: "emailing",
    domain_agents: ["campaign-agent", "audience-agent", "copy-agent", "deliverability-agent", "analytics-agent"],
  }),
  card({
    slug: "cms",
    name: "CMS",
    description: "Headless / Next.js-native CMS (Payload).",
    kind: "business",
    category: "content",
    stack: ["Next.js", "React", "TypeScript"],
    license: "MIT",
    source_github: "https://github.com/payloadcms/payload",
    source_name: "Payload CMS",
    create_app_id: "website",
    featured: true,
    domain_agents: ["content-agent", "seo-agent", "media-agent", "publisher-agent", "localization-agent"],
  }),
  card({
    slug: "saas-starter",
    name: "SaaS Starter",
    description: "Auth, teams, Stripe and dashboard starter.",
    kind: "business",
    category: "saas",
    stack: ["Next.js", "Postgres", "Stripe", "shadcn"],
    license: "MIT",
    source_github: "https://github.com/nextjs/saas-starter",
    source_name: "Next.js SaaS Starter",
    create_app_id: "saas",
    featured: true,
    domain_agents: ["onboarding-agent", "billing-agent", "admin-agent", "support-agent", "growth-agent"],
  }),
  card({
    slug: "restaurant-delivery",
    name: "Restaurant Delivery",
    description: "Food ordering storefront plus admin (Payload).",
    kind: "business",
    category: "hospitality",
    stack: ["Next.js", "Payload CMS", "MongoDB"],
    license: "MIT",
    source_github: "https://github.com/Shatlyk1011/food-delivery-app",
    source_name: "Ashpez Food Delivery",
    create_app_id: "restaurant",
    domain_agents: ["ordering-agent", "menu-agent", "delivery-agent", "promo-agent", "support-agent"],
  }),
  card({
    slug: "salon-spa",
    name: "Salon / Spa",
    description: "Multi-salon booking, services and reviews.",
    kind: "business",
    category: "booking",
    stack: ["Next.js", "MongoDB", "TypeScript"],
    license: "MIT",
    source_github: "https://github.com/harshanacz/salonbookinglk_platform",
    source_name: "SalonBooking.lk",
    create_app_id: "booking",
    domain_agents: ["booking-agent", "stylist-agent", "reminder-agent", "review-agent", "inventory-agent"],
  }),
  card({
    slug: "event-management",
    name: "Event Management",
    description: "Events, tickets and Stripe checkout.",
    kind: "business",
    category: "events",
    stack: ["Next.js", "MongoDB", "Clerk", "Stripe"],
    license: "MIT",
    source_github: "https://github.com/sanidhyy/evently",
    source_name: "Evently",
    create_app_id: null,
    domain_agents: ["event-agent", "ticketing-agent", "promotion-agent", "attendee-agent", "report-agent"],
  }),
  card({
    slug: "legal",
    name: "Legal Case Management",
    description: "Cases, hearings, parties and e-filing roles.",
    kind: "business",
    category: "legal",
    stack: ["Next.js", "Fastify", "Prisma", "PostgreSQL"],
    license: "MIT",
    source_github: "https://github.com/tpt-solutions/tpt-court",
    source_name: "TPT Court",
    create_app_id: "legal",
    domain_agents: ["case-agent", "deadline-agent", "document-agent", "hearing-agent", "client-update-agent"],
  }),
  card({
    slug: "travel-agency",
    name: "Travel Agency",
    description: "AI-assisted travel ops and lead handling.",
    kind: "business",
    category: "travel",
    stack: ["Next.js", "Firebase", "Vercel AI SDK"],
    license: "MIT",
    source_github: "https://github.com/Minato95-ayu/travel-os",
    source_name: "TravelOS",
    create_app_id: null,
    domain_agents: ["travel-advisor", "itinerary-agent", "quote-agent", "booking-agent", "follow-up-agent"],
  }),
  card({
    slug: "manufacturing",
    name: "Manufacturing / MRP",
    description: "BOM, production runs and factory inventory.",
    kind: "business",
    category: "manufacturing",
    stack: ["FastAPI", "Next.js", "PostgreSQL"],
    license: "MIT",
    source_github: "https://github.com/bryanadamg/terras-erp",
    source_name: "Teras ERP",
    create_app_id: "manufacturing",
    domain_agents: ["mrp-agent", "production-agent", "quality-agent", "procurement-agent", "inventory-agent"],
  }),
  card({
    slug: "ai-chat",
    name: "AI Chatbot",
    description: "Multi-provider chat, agents, MCP and artifacts. The main chatbot studio.",
    kind: "ai-product",
    category: "chat",
    stack: ["React", "Node", "MongoDB", "MCP"],
    license: "MIT",
    source_github: "https://github.com/danny-avila/LibreChat",
    source_name: "LibreChat",
    create_app_id: "chatbot",
    featured: true,
    domain_agents: ["chat-agent", "mcp-agent", "artifact-agent", "preset-agent", "moderation-agent"],
  }),
  card({
    slug: "ai-rag-chat",
    name: "RAG Workspace",
    description: "Chat with documents, agents and a no-code builder.",
    kind: "ai-product",
    category: "rag",
    stack: ["React", "Node", "RAG"],
    license: "MIT",
    source_github: "https://github.com/Mintplex-Labs/anything-llm",
    source_name: "AnythingLLM",
    create_app_id: "rag",
    featured: true,
    domain_agents: ["workspace-agent", "ingestion-agent", "rag-agent", "agent-builder", "connector-agent"],
  }),
  card({
    slug: "ai-search",
    name: "AI Search",
    description: "Perplexity-style search with cited sources.",
    kind: "ai-product",
    category: "search",
    stack: ["Next.js", "TypeScript"],
    license: "MIT",
    source_github: "https://github.com/ItzCrazyKns/Perplexica",
    source_name: "Perplexica",
    create_app_id: "research",
    featured: true,
    domain_agents: ["search-agent", "citation-agent", "follow-up-agent", "brief-agent", "source-ranker"],
  }),
  card({
    slug: "ai-chat-ui",
    name: "ChatGPT-style UI",
    description: "Lightweight one-click chat UI for many models.",
    kind: "ai-product",
    category: "chat",
    stack: ["Next.js", "React"],
    license: "MIT",
    source_github: "https://github.com/ChatGPTNextWeb/NextChat",
    source_name: "NextChat",
    create_app_id: "chatbot",
    featured: true,
    domain_agents: ["chat-agent", "prompt-agent", "model-router", "export-agent", "theme-agent"],
  }),
  card({
    slug: "document-rag",
    name: "Document RAG",
    description: "QA over files with collections and citations.",
    kind: "ai-product",
    category: "rag",
    stack: ["Python", "Gradio", "RAG"],
    license: "Apache-2.0",
    source_github: "https://github.com/Cinnamon/kotaemon",
    source_name: "Kotaemon",
    create_app_id: "rag",
    featured: true,
    domain_agents: ["ingestion-agent", "qa-agent", "citation-agent", "collection-agent", "share-agent"],
  }),
  card({
    slug: "coding-agent",
    name: "Coding Agent",
    description: "Software agent with UI over code, terminal and files.",
    kind: "ai-product",
    category: "agents",
    stack: ["Python", "React"],
    license: "MIT",
    source_github: "https://github.com/All-Hands-AI/OpenHands",
    source_name: "OpenHands",
    create_app_id: "agent",
    featured: true,
    domain_agents: ["coding-agent", "review-agent", "test-agent", "terminal-agent", "pr-agent"],
  }),
  card({
    slug: "browser-agent",
    name: "Browser Agent",
    description: "Agent that drives a real browser.",
    kind: "ai-product",
    category: "agents",
    stack: ["Python", "Gradio"],
    license: "MIT",
    source_github: "https://github.com/browser-use/web-ui",
    source_name: "Browser Use WebUI",
    create_app_id: "scraping",
    featured: true,
    domain_agents: ["browser-agent", "form-agent", "extract-agent", "watch-agent", "report-agent"],
  }),
  card({
    slug: "social-media-ai",
    name: "Social Media AI",
    description: "AI content plus scheduling for YouTube and TikTok.",
    kind: "ai-product",
    category: "social",
    stack: ["Next.js", "Prisma", "PostgreSQL"],
    license: "MIT",
    source_github: "https://github.com/Anil-matcha/Free-AI-Social-Media-Scheduler",
    source_name: "Free AI Social Media Scheduler",
    create_app_id: "social",
    domain_agents: ["copy-agent", "schedule-agent", "publish-agent", "analytics-agent", "repurpose-agent"],
  }),
];

export const AWS_TEMPLATES_CATALOG_URL =
  "https://navinagent.s3.eu-north-1.amazonaws.com/templates/v1/catalog.json";

export const STUDIO_CATEGORIES = new Set(["chat", "rag", "agents", "search"]);

export type TemplateBucket = "chat" | "rag" | "agents" | "business";

/** One real gallery bucket per template. Business first, then RAG / Chat / Agents IA. */
export function templateBucket(row: { kind: string; category: string }): TemplateBucket {
  if (row.kind === "business") return "business";
  if (row.category === "rag") return "rag";
  if (row.category === "chat" || row.category === "search") return "chat";
  return "agents";
}

export async function fetchAwsAppTemplatesCatalog(): Promise<AppTemplateSummary[] | null> {
  try {
    const response = await fetch(AWS_TEMPLATES_CATALOG_URL, { cache: "no-store" });
    if (!response.ok) return null;
    const payload = (await response.json()) as { templates?: AppTemplateSummary[] };
    if (!Array.isArray(payload.templates) || payload.templates.length === 0) return null;
    return payload.templates;
  } catch {
    return null;
  }
}

export function mergeAppTemplates(
  remote: AppTemplateSummary[],
  fallback: AppTemplateSummary[] = APP_TEMPLATES_FALLBACK,
): AppTemplateSummary[] {
  const bySlug = new Map<string, AppTemplateSummary>();
  for (const row of fallback) bySlug.set(row.slug, row);
  for (const row of remote) bySlug.set(row.slug, row);
  return [...bySlug.values()].sort((a, b) => {
    if (a.featured !== b.featured) return a.featured ? -1 : 1;
    const aStudio = STUDIO_CATEGORIES.has(a.category) ? 0 : 1;
    const bStudio = STUDIO_CATEGORIES.has(b.category) ? 0 : 1;
    if (aStudio !== bStudio) return aStudio - bStudio;
    return a.name.localeCompare(b.name);
  });
}
