export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

export type UITurnPhase = "user" | "reasoning" | "activity" | "answer" | "complete";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "audio" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessageSource { kind: "cron" | "local_trigger" | "trigger" | string; label?: string; }

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** Structured tool events behind trace rows. Kept so activity cards can
   * distinguish running, completed, and failed tool phases. */
  toolEvents?: ToolProgressEvent[];
  /** Activity rows: explicit file edits emitted by edit tools. */
  fileEdits?: UIFileEdit[];
  /** Activity rows created during the same agent phase share one collapsible block. */
  activitySegmentId?: string;
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** App-specific CLI adapters explicitly attached to this user turn. */
  cliApps?: UICliAppAttachment[];
  /** Settings-managed MCP presets explicitly attached to this user turn. */
  mcpPresets?: UIMcpPresetAttachment[];
  /** Document template (PPT/Word/PDF/Excel) picked for this user turn. */
  documentTemplate?: UIDocumentTemplateAttachment;
  /** Marketing / Montage AWS media template picked for this user turn. */
  mediaTemplate?: UIMediaTemplateAttachment;
  /** All media references attached to this user turn (max 6). */
  mediaTemplates?: UIMediaTemplateAttachment[];
  /** Assistant turn: accumulated model reasoning / thinking text. Built up
   * incrementally from ``reasoning_delta`` frames; finalized when
   * ``reasoning_end`` arrives. */
  reasoning?: string;
  /** True while ``reasoning_delta`` frames are still arriving for this turn.
   * Drives the shimmer header on ``ReasoningBubble``. */
  reasoningStreaming?: boolean;
  /** End-to-end wall time for this assistant turn (persisted ``latency_ms`` / ``turn_end``). */
  latencyMs?: number;
  /** Per-phase wall times from the agent state machine (``phase_timings_ms`` on ``turn_end``). */
  phaseTimingsMs?: Record<string, number>;
  /** Model id that produced this assistant turn (stable across later picker changes). */
  modelName?: string;
  /** Display label captured when the turn ran (preset label when available). */
  modelLabel?: string;
  /** Task-routing role that selected the model (deep, fast, review...). */
  taskRole?: string;
  /** Lightweight provenance for proactive assistant messages. */
  source?: UIMessageSource;
  /** Stable protocol metadata for grouping all activity emitted by one user turn. */
  turnId?: string;
  turnPhase?: UITurnPhase;
  turnSeq?: number;
}

export interface UICliAppAttachment {
  name: string;
  display_name?: string;
  category?: string;
  entry_point?: string;
  logo_url?: string | null;
  brand_color?: string | null;
}

export interface DocumentTemplateModule {
  id: string;
  title: string;
  required?: boolean;
}

export interface UIMediaTemplateAttachment {
  id: string;
  title?: string;
  kind?: string;
  format?: string;
  family?: string;
}

export interface MediaTemplateItem {
  id: string;
  title: string;
  studio: string[];
  kind: "image" | "video";
  family: string;
  tab: string;
  tags: string[];
  format: string;
  premium: boolean;
  intent?: string;
  hint?: string;
  s3_key: string;
  url: string;
  preview_url: string;
}

export interface MediaTemplatesPayload {
  schema: string;
  source: string;
  s3_prefix: string;
  base_url: string;
  families: string[];
  formats: string[];
  items: MediaTemplateItem[];
}

export interface UIDocumentTemplateAttachment {
  category: string;
  name: string;
  title?: string;
  /** Explicit output language selected for this generated document. */
  language?: string;
  kind?: string;
  output_formats?: string[];
  language_mode?: string;
  text_policy?: string;
  image_text_policy?: string;
  modules?: DocumentTemplateModule[];
}

export interface DocumentTemplateInfo {
  category: string;
  name: string;
  title: string;
  description?: string;
  item_count: number;
  files?: string[];
  preview_url?: string;
  kind?: string;
  output_formats?: string[];
  language_mode?: string;
  text_policy?: string;
  image_text_policy?: string;
  modules?: DocumentTemplateModule[];
}

export interface DocumentTemplatesPayload {
  categories: { id: string; templates: DocumentTemplateInfo[] }[];
}

export interface UIMcpPresetAttachment {
  name: string;
  display_name?: string;
  category?: string;
  transport?: string;
  status?: string;
  configured?: boolean;
  logo_url?: string | null;
  brand_color?: string | null;
}

export interface SessionAutomationJob {
  id: string;
  name: string;
  enabled: boolean;
  protected?: boolean;
  delete_after_run?: boolean;
  created_at_ms?: number | null;
  updated_at_ms?: number | null;
  kind?: "local_trigger" | "cron" | string;
  /** Set for a system loop, so the client owns its wording. */
  system_key?: string | null;
  schedule: {
    kind: "at" | "every" | "cron" | "local" | string;
    at_ms?: number | null;
    every_ms?: number | null;
    expr?: string | null;
    tz?: string | null;
    /** Present when the expression matches a preset the editor can reopen. */
    recurrence?: LoopRecurrence | null;
  };
  limits?: LoopLimits;
  payload: {
    message: string;
    kind?: "agent_turn" | "system_event" | "local_trigger" | string;
    command?: string;
  };
  state: {
    next_run_at_ms?: number | null;
    last_run_at_ms?: number | null;
    last_status?: "ok" | "error" | "skipped" | string | null;
    last_error?: string | null;
    pending?: boolean;
    /** Set when the service paused the loop itself, with the reason. */
    paused_reason?: string | null;
    consecutive_failures?: number;
    tokens_today?: number;
    tokens_day?: string | null;
    run_history?: Array<{
      run_at_ms: number;
      status: "ok" | "error" | "skipped" | string;
      duration_ms?: number;
      error?: string | null;
      tokens?: number;
    }>;
  };
  origin?: {
    session_key?: string;
    channel: string;
    chat_id?: string;
    title?: string;
    preview?: string;
  } | null;
  trigger?: {
    id: string;
    command: string;
  };
}

export interface SessionAutomationsPayload { jobs: SessionAutomationJob[]; }
export interface AutomationsPayload { jobs: SessionAutomationJob[]; }
/** A repeating schedule anchored to the wall clock, as the server compiles it. */
export type LoopRecurrenceKind =
  | "minutes"
  | "hourly"
  | "every_hours"
  | "daily"
  | "weekly"
  | "monthly";

export interface LoopRecurrence {
  kind: LoopRecurrenceKind;
  /** Minutes or hours, depending on kind. */
  interval: number;
  minute: number;
  hour: number;
  /** 1=Monday through 7=Sunday. */
  weekday: number;
  /** Day of the month, or "last" for whichever day ends it. */
  day: number | "last";
  tz?: string | null;
}

export interface LoopLimits {
  /** Skip runs once the day's spend reaches this; 0 means no ceiling. */
  daily_token_budget: number;
  /** Pause after this many failures in a row; 0 defers to the global setting. */
  max_consecutive_failures: number;
}

export interface AutomationUpdatePayload {
  name?: string;
  message?: string;
  schedule?: {
    kind: "at" | "every" | "cron" | "recurrence";
    at_ms?: number;
    every_ms?: number;
    expr?: string;
    tz?: string;
    recurrence?: LoopRecurrence;
  };
  limits?: LoopLimits;
}

export interface SessionDeleteResult {
  deleted: boolean;
  blocked_by_automations?: boolean;
  automations?: SessionAutomationJob[];
}

export interface SkillSummary {
  name: string;
  description: string;
  source: "workspace" | "builtin" | string;
  category?: string;
  default_for?: string | null;
  available: boolean;
  unavailable_reason?: string;
  editable?: boolean;
  deletable?: boolean;
}

export interface PluginPackSummary {
  name: string;
  display_name: string;
  version: string;
  description: string;
  author: string;
  homepage: string;
  source: string;
  enabled: boolean;
  skills: string[];
  mcp_servers: string[];
}

export interface PluginPacksPayload {
  plugins: PluginPackSummary[];
  dest?: string;
  copied?: string[];
  previews?: SkillPreviewPayload[];
}

export interface SkillRequirements {
  bins: string[];
  env: string[];
  missing_bins: string[];
  missing_env: string[];
}

export interface SkillSetupOption {
  id: string;
  kind: string;
  label: string;
  runnable: boolean;
  command: string;
}

export interface SkillSetupInfo {
  can_setup: boolean;
  options: SkillSetupOption[];
}

export interface SkillDetail extends SkillSummary {
  requirements: SkillRequirements;
  setup?: SkillSetupInfo;
  raw_markdown: string;
}

export interface SkillSetupResult {
  ok: boolean;
  message: string;
  output: string;
  skill: SkillDetail;
}

export interface SkillsPayload { skills: SkillSummary[]; }

export interface SkillPreviewPayload {
  name: string;
  description: string;
  markdown: string;
  origin?: string;
}

export interface WorkspaceSkillCandidate {
  name: string;
  description: string;
  origin: string;
  already: boolean;
  markdown?: string;
}

export type SkillApplyScope = "workspace" | "everywhere";

export interface WorkspaceSkillsDiscoverPayload {
  root: string;
  dest?: string;
  skills: WorkspaceSkillCandidate[];
}

export interface WorkspaceSkillsImportPayload extends PluginPacksPayload, SkillsPayload {
  ok: boolean;
  imported: string[];
  skipped: Array<{ name: string; reason: string }>;
  dest?: string;
  previews?: SkillPreviewPayload[];
}

export type AppTemplateKind = "business" | "ai-product";
export type AppTemplateStatus = "source" | "normalized";
export type AppTemplateAuditStatus = "pending" | "in_review" | "passed" | "rejected";

export interface AppTemplateSummary {
  slug: string;
  name: string;
  description: string;
  kind: AppTemplateKind;
  category: string;
  stack: string[];
  license: "MIT" | "Apache-2.0";
  source_github: string;
  source_name: string;
  create_app_id: string | null;
  featured: boolean;
  status: AppTemplateStatus;
  audit_status: AppTemplateAuditStatus;
  universal_agents: string[];
  domain_agents: string[];
  installed: boolean;
  local_cache: boolean;
  can_publish: boolean;
  aws_key: string;
  aws_url?: string;
}

export interface AppTemplatesPayload {
  templates: AppTemplateSummary[];
  installed: string[];
  aws_prefix: string;
  aws_base_url?: string;
  aws_catalog_url?: string;
  source?: "aws" | "builtin";
  publish_policy: string;
}

export interface AppTemplateActionResult {
  ok: boolean;
  action: "install" | "create";
  slug: string;
  workspace?: string;
  dest?: string;
  plugin_dir: string;
  already_installed?: boolean;
  copied_source?: boolean;
  audit_status: AppTemplateAuditStatus;
  status: AppTemplateStatus;
  can_publish: boolean;
  preview_url?: string | null;
  started?: string[];
  bootstrap?: {
    env?: string;
    databases?: string[];
    packages?: string[];
    started?: string[];
    preview_url?: string | null;
    playbook?: boolean;
    has_source?: boolean;
  };
}

export interface SkillCreateInput {
  name: string;
  description: string;
  markdown?: string;
}

/** Structured UI blob on ``progress`` WS frames; channels may add more ``kind`` values later. */
export interface AgentUIBlob {
  kind: string;
  data?: unknown;
}

/** ``agent_ui.kind === "task_progress"`` payload for bars / ETA / step labels. */
export interface TaskProgressData {
  call_id?: string;
  label: string;
  percent?: number;
  indeterminate?: boolean;
  eta_s?: number;
  step?: string;
  step_index?: number;
  steps_total?: number;
}

/** WebSocket snapshot for sustained goals (`goal_state` events; keyed by ``chat_id``). */
export interface GoalStateWsPayload {
  active: boolean;
  ui_summary?: string;
  objective?: string;
}

export interface ToolProgressEvent {
  version?: number;
  phase?: "start" | "output" | "end" | "error" | string;
  call_id?: string;
  name?: string;
  arguments?: unknown;
  result?: unknown;
  error?: unknown;
  files?: unknown[];
  embeds?: unknown[];
  /** Live cumulative output tail while the tool is still running (phase "output"). */
  output?: unknown;
  /** 0-100 when the tool reports determinate progress. */
  percent?: number;
  /** When true (or percent omitted while running), render an indeterminate bar. */
  indeterminate?: boolean;
  /** Estimated seconds remaining, when known. */
  eta_s?: number;
  /** Short human label for the current phase (Downloading…, Building…). */
  label?: string;
  /** Client-side arrival time of the "start" phase (live duration display). */
  client_started_at?: number;
  /** Client-side arrival time of the "end"/"error" phase. */
  client_ended_at?: number;
  /** OS sandbox backend a shell command runs in ("native", "bwrap"); absent when unconfined. */
  sandbox?: string;
  /** True when the user approved lifting the configured sandbox for this one command. */
  sandbox_lifted?: boolean;
}

export interface UIFileDiff {
  format: "unified" | string;
  context?: number;
  truncated?: boolean;
  text?: string;
}

export interface UIFileEdit {
  version?: number;
  call_id: string;
  tool: string;
  path: string;
  absolute_path?: string;
  phase?: "start" | "end" | "error" | string;
  added: number;
  deleted: number;
  approximate?: boolean;
  status: "editing" | "done" | "error";
  operation?: "edit" | "delete" | string;
  binary?: boolean;
  error?: string;
  pending?: boolean;
  diff?: UIFileDiff;
}

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  title?: string;
  preview: string;
  /** Unix epoch seconds when this session currently has a turn in flight. */
  runStartedAt?: number | null;
  workspaceScope?: WorkspaceScopePayload | null;
}

export type WorkspaceAccessMode = "restricted" | "full";
export type WebuiDefaultAccessMode = "default" | "full";

export interface WorkspaceScopePayload {
  project_path: string;
  project_name?: string;
  access_mode: WorkspaceAccessMode;
  restrict_to_workspace?: boolean;
  sandbox_status?: {
    restrict_to_workspace: boolean;
    workspace_root: string;
    level: string;
    enforced: boolean;
    provider: string;
    provider_label: string;
    summary: string;
  };
}

export interface WorkspacesPayload {
  schema_version: number;
  default_access_mode: WebuiDefaultAccessMode;
  default_scope: WorkspaceScopePayload;
  controls: {
    can_change_project: boolean;
    can_use_full_access: boolean;
  };
}

export type SidebarDensity = "comfortable" | "compact";
export type SidebarSortMode = "updated_desc" | "created_desc" | "title_asc";

export interface SidebarViewState {
  density: SidebarDensity;
  show_previews: boolean;
  show_timestamps: boolean;
  show_archived: boolean;
  sort: SidebarSortMode;
  /** Mirrored server-side so the CLI can match the app window frame to it. */
  theme: "dark" | "light";
}

export interface SidebarStatePayload {
  schema_version: number;
  pinned_keys: string[];
  archived_keys: string[];
  /** Manual order of unpinned chats. Pinned order lives in ``pinned_keys``. */
  chat_order: string[];
  title_overrides: Record<string, string>;
  project_name_overrides: Record<string, string>;
  tags_by_key: Record<string, string[]>;
  /** Last product module where each chat was used (e.g. ``dev`` for Code). */
  module_by_key: Record<string, string>;
  /** Module a project folder belongs to, keyed by folder path. */
  module_by_path: Record<string, string>;
  collapsed_groups: Record<string, boolean>;
  recent_projects?: RecentProjectEntry[];
  view: SidebarViewState;
  updated_at?: string | null;
}

export interface RecentProjectEntry {
  path: string;
  name: string;
}

export interface MetagraphNode {
  id: string;
  kind: string;
  size: number;
  role?: string;
  /** "auto" when derived from a docstring, "manual" from .navin/metadata/index.json. */
  role_source?: "auto" | "manual";
  /** The file changed after its role was recorded, so the role may be wrong. */
  role_stale?: boolean;
  symbols?: number;
  in_degree: number;
  out_degree: number;
}

export interface MetagraphEdge {
  source: string;
  target: string;
}

export interface MetagraphCluster {
  id: string;
  label: string;
  member_ids: string[];
  kind?: string;
}

export interface MetagraphPosition {
  x: number;
  y: number;
}

export interface MetagraphDiff {
  added_nodes?: MetagraphNode[];
  removed_nodes?: string[];
  updated_nodes?: MetagraphNode[];
  added_edges?: MetagraphEdge[];
  removed_edges?: MetagraphEdge[];
  generation?: number;
  positions?: Record<string, MetagraphPosition>;
  layout_width?: number;
  layout_height?: number;
}

export interface MetagraphPayload {
  project_path: string;
  generation?: number;
  view?: "files" | "packages" | string;
  nodes: MetagraphNode[];
  edges: MetagraphEdge[];
  kinds: Record<string, number>;
  has_metadata: boolean;
  annotated: number;
  annotated_manual?: number;
  /** Recorded roles whose file changed since; they describe replaced code. */
  annotated_stale?: number;
  /**
   * "git" when .gitignore was honored, "walk" when the tree was walked because
   * the repo ignores everything and whitelists exceptions. Worth showing: a file
   * count only means "the whole project" once you know how files were found.
   */
  discovery?: string;
  truncated: boolean;
  /** Files discovered before the display cap was applied. */
  total_files?: number;
  symbols?: number;
  /** Server-side force layout (native engine). Absent => client layout. */
  positions?: Record<string, MetagraphPosition>;
  layout_width?: number;
  layout_height?: number;
  clusters?: MetagraphCluster[];
  engine?: "native" | "python" | string;
}

export interface ProjectSymbol {
  name: string;
  qualname?: string;
  kind: string;
  detail?: string;
  path: string;
  line: number;
  /** Defined in the current file or one it imports. */
  in_scope?: boolean;
}

export interface ProjectSymbolsPayload {
  query: string;
  items: ProjectSymbol[];
  total: number;
}

/** A file or folder offered by the composer's @-mention palette. */
export interface ProjectFileMatch {
  /** Workspace-relative path, always forward-slashed. */
  path: string;
  name: string;
  kind: "file" | "directory" | "symbol";
  /** 1-based definition line, for `kind === "symbol"`. */
  line?: number;
  /** What the index calls it: function, class, interface, method… */
  symbolKind?: string;
}

export interface ProjectFileSearchPayload {
  query: string;
  items: ProjectFileMatch[];
  total: number;
}

/** Ghost-text suggestion for the current caret position. */
export interface InlineCompletionPayload {
  completion: string;
  model: string;
  /** Why nothing was suggested, when `completion` is empty. */
  reason?: string;
  /** Model route used (code / code-fast / fast / …). */
  route?: string;
  /** End-to-end server wall time for the assist call. */
  latency_ms?: number;
  /** Time to first token when streamed. */
  ttft_ms?: number;
}

/** Replacement code produced by a Cmd+K instruction. */
export interface InlineEditPayload {
  replacement: string;
  model: string;
  original_length: number;
  route?: string;
  latency_ms?: number;
  ttft_ms?: number;
}

/** Timing / routing metadata from a Tab or Cmd+K assist call. */
export interface AssistMeta {
  model?: string;
  route?: string;
  latency_ms?: number;
  ttft_ms?: number;
}

export interface ProjectSearchMatch {
  line: number;
  col: number;
  text: string;
}

export interface ProjectSearchFile {
  path: string;
  matches: ProjectSearchMatch[];
}

export interface ProjectSearchPayload {
  root: string;
  query: string;
  tool: string;
  /** ``semantic`` when embedding search was used; omitted for lexical. */
  mode?: string;
  truncated: boolean;
  total: number;
  files: ProjectSearchFile[];
}

export interface ProjectReplacePayload {
  root: string;
  query: string;
  replacements: number;
  files_changed: number;
  files: { path: string; replacements: number }[];
}

export interface GitChangeEntry {
  path: string;
  xy: string;
  status: string;
  staged: boolean;
}

export interface GitStashEntry {
  index: number;
  label: string;
  message: string;
}

export interface GitChangesPayload {
  available: boolean;
  is_repo: boolean;
  files: GitChangeEntry[];
  branch?: string;
  has_upstream?: boolean;
  ahead?: number;
  behind?: number;
  merge_in_progress?: boolean;
  rebase_in_progress?: boolean;
  stash_count?: number;
  stashes?: GitStashEntry[];
}

export interface GitCommitPayload {
  committed: boolean;
  pushed: boolean;
  detail?: string;
  branch?: string;
  has_upstream?: boolean;
  ahead?: number;
  behind?: number;
}

export interface GitBranchPayload {
  op: "list" | "create" | "checkout" | string;
  branches?: string[];
  current?: string;
  branch?: string;
  has_upstream?: boolean;
  ahead?: number;
  behind?: number;
}

export interface GithubChecksSummary {
  state: "success" | "failure" | "pending" | "unknown" | string;
  total: number;
  passing: number;
  failing: number;
  pending: number;
  items: Array<{ name: string; state: string; url?: string | null }>;
}

/** Which forge hosts `origin`. Drives wording (PR vs MR) and token hints. */
export type ForgeKind = "github" | "gitlab" | "forgejo" | "unknown";

/**
 * Forge identity shared by every PR/CI payload. Opening a request no longer
 * needs the `gh` CLI, so the panel has to say which forge it is talking to
 * and whether a token for that host exists.
 */
export interface ForgeIdentity {
  forge?: ForgeKind;
  forge_label?: string;
  /** "pull request" on GitHub/Forgejo, "merge request" on GitLab. */
  request_label?: string;
  host?: string;
  repo?: string;
  token_configured?: boolean;
  /** "settings" | "env:NAME" | "gh" | "" - never the token itself. */
  token_source?: string;
  gh_available?: boolean;
}

export interface GithubCiStatusPayload extends ForgeIdentity {
  available: boolean;
  branch: string;
  pr_url: string | null;
  pr_number?: number | null;
  detail: string;
  checks: GithubChecksSummary;
}

export interface GithubPrViewPayload extends ForgeIdentity {
  available: boolean;
  branch: string;
  detail: string;
  pr: {
    url: string;
    number: number;
    title: string;
    state: string;
    is_draft: boolean;
    head: string;
    base: string;
    checks: GithubChecksSummary;
  } | null;
}

export interface GithubPrCreatePayload extends ForgeIdentity {
  ok: boolean;
  created: boolean;
  pr_url: string | null;
  detail: string;
  branch?: string;
  is_draft?: boolean;
  pr_number?: number | null;
  /** Short HEAD sha at open/reuse time (board continuity). */
  head_sha?: string | null;
}

export interface GithubPrSyncSuggestion {
  task_id: string;
  pr_url: string;
  merged: boolean;
  merged_at?: string | null;
  detail?: string;
}

export interface GithubPrSyncPayload {
  ok: boolean;
  available: boolean;
  project_path?: string;
  suggestions: GithubPrSyncSuggestion[];
  detail: string;
}

export interface GithubFixCiPayload {
  available: boolean;
  branch: string;
  pr_url: string | null;
  failing: number;
  prompt: string;
  detail: string;
}

export interface DebugStackFrame {
  id: number;
  name: string;
  path: string;
  line: number;
  column: number;
}

export interface DebugVariable {
  name: string;
  value: string;
  type?: string | null;
  variablesReference: number;
}

export interface DebugScope {
  name: string;
  variablesReference: number;
  expensive?: boolean;
}

export interface DebugStatePayload {
  ok?: boolean;
  state: "idle" | "starting" | "running" | "stopped" | "terminated" | string;
  program?: string | null;
  thread_id?: number | null;
  stopped_reason?: string | null;
  stopped_frame?: DebugStackFrame | null;
  breakpoints?: Array<{ path: string; lines: number[] }>;
  console?: string[];
  alive?: boolean;
  frames?: DebugStackFrame[];
  scopes?: DebugScope[];
  variables?: DebugVariable[];
  result?: string;
}

export interface GitLogCommit {
  hash: string;
  short: string;
  /** Parent hashes; 2+ entries mean a merge commit. */
  parents: string[];
  author: string;
  email: string;
  /** ISO-8601 author date. */
  date: string;
  /** Decorating refs (branch names, tags) pointing at this commit. */
  refs: string[];
  subject: string;
  /** True when the commit is reachable from a remote branch. */
  pushed: boolean;
}

export interface GitLogBranch {
  name: string;
  tip: string;
  date: string;
  author: string;
  remote: boolean;
}

export interface GitLogPayload {
  available: boolean;
  is_repo: boolean;
  commits: GitLogCommit[];
  branches: GitLogBranch[];
  head?: string;
  total?: number;
  branch?: string;
  has_upstream?: boolean;
  ahead?: number;
  behind?: number;
}

export interface GitCommitFileStat {
  path: string;
  additions: number;
  deletions: number;
  binary: boolean;
}

export interface GitCommitDetailPayload {
  hash: string;
  author: string;
  email: string;
  date: string;
  committer: string;
  committed_date: string;
  message: string;
  files: GitCommitFileStat[];
  additions: number;
  deletions: number;
}

export interface GitDiffPayload {
  path: string;
  /** The other side when comparing two files, null when diffing against HEAD. */
  against?: string | null;
  untracked: boolean;
  ignore_whitespace?: boolean;
  diff: string;
}

/** One line of ``git blame --line-porcelain`` for the editor strip. */
export interface GitBlameLine {
  line: number;
  commit: string;
  author: string;
  email?: string;
  date?: string;
  summary?: string;
}

export interface GitBlamePayload {
  path: string;
  items: GitBlameLine[];
  total: number;
  available: boolean;
  reason?: string;
}

export type ReviewChangeStatus = "created" | "modified" | "deleted";

export interface ReviewChangeEntry {
  path: string;
  display_path: string;
  status: ReviewChangeStatus;
  updated_at?: string;
  /** Lines added/removed by the pending change; 0 for binary and deleted files. */
  added?: number;
  deleted?: number;
}

export interface ReviewChangesPayload {
  changes: ReviewChangeEntry[];
}

/**
 * One independently acceptable change within a pending file.
 *
 * `id` carries both the position and a digest of the content, so the server can
 * refuse a click that raced the agent instead of reverting the wrong lines. Line
 * indices are 0-based; `new_start` locates the hunk in the current document,
 * which is what the editor renders.
 */
export interface ReviewHunk {
  id: string;
  old_start: number;
  old_count: number;
  new_start: number;
  new_count: number;
  added: number;
  deleted: number;
}

export interface ReviewFilePayload {
  path: string;
  status: ReviewChangeStatus;
  binary: boolean;
  baseline: string | null;
  current: string | null;
  /** Empty for binary and deleted files, which stay whole-file decisions. */
  hunks?: ReviewHunk[];
}

export interface ReviewActionPayload {
  action: "accept" | "reject";
  count: number;
  restored?: number;
  deleted?: number;
  /** Present on a per-hunk action. */
  hunk?: string;
  /** Hunks still awaiting a decision on this file. */
  remaining?: number;
  /** The file left the review queue entirely. */
  done?: boolean;
}

export interface ExecPolicyBuiltinRule {
  pattern: string;
  label: string;
}

export type ExecApprovalMode = "autonomous" | "risky" | "always";

export interface ExecPolicyPayload {
  exec_enabled: boolean;
  restrict_to_workspace: boolean;
  allow_patterns: string[];
  deny_patterns: string[];
  builtin_deny: ExecPolicyBuiltinRule[];
  builtin_deny_enabled: boolean;
  approval_mode?: ExecApprovalMode;
  hot_reload?: { ok: boolean; requires_restart?: boolean; message?: string };
}

export interface FsRootEntry {
  /** workspace | home | windows-home | windows | disk | wsl | volume | drive | system */
  kind: string;
  /** English wording; the UI rewords known kinds from `name`. */
  label: string;
  path: string;
  /** The varying part: drive letter, volume or distribution name. */
  name?: string;
}

export interface FsRootsPayload {
  environment: "wsl" | "linux" | "macos" | "windows" | string;
  /** WSL distribution name (e.g. "Ubuntu"), present when environment is "wsl". */
  distro?: string;
  roots: FsRootEntry[];
}

export interface ContextUsageBucket {
  id: string;
  label: string;
  tokens: number;
}

export interface ContextUsageIncluded {
  path: string;
  /** Why the path is packed into Agent Code context. */
  reason: "open_file" | "git_dirty" | "file_mention" | "project_rules" | string;
}

export interface ContextUsagePayload {
  /** Attributed prompt fill (profile total, else last peak, else messages). */
  tokens: number;
  /** Tokens from persisted chat messages only (excludes system/tools). */
  message_tokens?: number;
  context_window: number | null;
  /** tokens / context_window, capped at 100. Null when the window is unknown. */
  percent: number | null;
  messages: number;
  /** Navin prompt-profile buckets. Empty when only a peak total is known. */
  buckets?: ContextUsageBucket[];
  /** Paths packed into the last user turn, when the Code module recorded them. */
  included?: ContextUsageIncluded[];
  /** How tokens were derived: provider | last_turn | estimate | messages */
  source?: string;
  peak_prompt_tokens?: number | null;
  /** Cumulative billed tokens for this session (sum of turn usages). */
  billed_tokens_session?: number | null;
}

export interface FsListPayload {
  path: string;
  parent: string | null;
  directories: Array<{ name: string; path: string }>;
  truncated: boolean;
}

export interface GitStatusPayload {
  available: boolean;
  is_repo: boolean;
  branch?: string;
  detached?: boolean;
  ahead?: number;
  behind?: number;
  staged?: number;
  unstaged?: number;
  untracked?: number;
  dirty?: boolean;
}

export interface GitClonePayload {
  path: string;
  name: string;
  url: string;
  reused?: boolean;
}

export interface FileDiagnostic {
  line: number;
  col: number;
  end_line: number;
  end_col: number;
  severity: "error" | "warning";
  code: string;
  message: string;
}

export interface FileDiagnosticsPayload {
  path: string;
  supported: boolean;
  tool: string;
  errors: number;
  warnings: number;
  diagnostics: FileDiagnostic[];
}

/** Project-wide diagnostics (workspace-mode LSP), keyed by absolute path. */
export interface WorkspaceDiagnosticsPayload {
  root: string;
  supported: boolean;
  errors: number;
  warnings: number;
  file_count: number;
  files: Record<string, FileDiagnosticsPayload>;
  diagnostics: Array<FileDiagnostic & { path: string }>;
}

export type AuditSeverity = "critical" | "high" | "medium" | "low";
export type AuditConfidence = "high" | "medium" | "low";

export interface AuditFinding {
  id: string;
  severity: AuditSeverity;
  category: string;
  message: string;
  recommendation: string;
  file: string;
  line: number;
  snippet: string;
  /** How sure Vision 360 is - low-confidence items do not lower the score. */
  confidence?: AuditConfidence;
  /** Short proof of why this finding was raised (AST path, motif, counts…). */
  evidence?: string;
}

export interface AuditFindingsSection {
  score: number;
  summary: Record<AuditSeverity, number>;
  findings: AuditFinding[];
  scored_findings?: number;
  engine?: string;
}

export interface AuditApiModule {
  module: string;
  framework: string;
  endpoints: AuditEndpoint[];
  auth_coverage?: number;
}

export interface AuditEndpoint {
  method: string;
  path: string;
  line: number;
  handler: string;
  auth: boolean;
  auth_scope?: string;
}

export interface AuditSqlQuery {
  file: string;
  line: number;
  kind: string;
  sql: string;
  risky: boolean;
  risk_reason: string;
  tables?: string[];
  parameterized?: boolean;
  source?: "sql-file" | "embedded";
  issue_ids?: string[];
}

export interface AuditNote {
  kind: "risk" | "strength" | "action" | "info";
  title: string;
  body: string;
}

export interface ProjectAuditPayload {
  generated_at: string;
  duration_ms: number;
  project: { name: string; path: string };
  overview: {
    git: {
      is_repo: boolean;
      branch?: string;
      dirty?: boolean;
      commit_count?: number | null;
      last_commits?: Array<{ hash: string; author: string; date: string; message: string }>;
      contributors?: Array<{ name: string; commits: number }>;
    };
    totals: { files: number; lines: number; code_lines: number; bytes: number };
    languages: Array<{ name: string; files: number; lines: number; percent: number }>;
    stack: string[];
    dependencies: {
      managers: Array<{
        name: string;
        file: string;
        runtime: number;
        dev: number;
        packages: string[];
      }>;
      lockfiles: string[];
    };
    tests: { files: number };
    docs: { files: number };
    todos: { todo: number; fixme: number; hack: number };
    largest_files: Array<{ path: string; lines: number; bytes: number }>;
    api_endpoints: number;
    sql_queries: number;
    sql_files?: number;
    scores: { security: number; performance: number; sql?: number };
    health_score: number;
  };
  api: {
    total: number;
    modules: AuditApiModule[];
    frameworks: string[];
  };
  openapi: {
    specs: Array<{
      path: string;
      title: string;
      version: string;
      endpoints: Array<{ method: string; path: string; summary: string }>;
    }>;
  };
  architecture: {
    mermaid: string;
    layers: Array<{ name: string; dirs: string[]; files: number }>;
    stack: string[];
    sql_files?: number;
  };
  permissions: {
    mechanisms: Array<{ kind: string; name: string; file: string; line: number; snippet: string }>;
    roles: Array<{ name: string; occurrences: number }>;
    protected_endpoints: number;
    unprotected_endpoints: Array<{ method: string; path: string; module: string; line: number }>;
    unprotected_count: number;
    coverage_percent?: number;
    module_auth_endpoints?: number;
  };
  sql: {
    total: number;
    by_kind: Record<string, number>;
    by_source?: Record<string, number>;
    queries: AuditSqlQuery[];
    files_scanned?: number;
    indexed_tables?: string[];
    findings?: AuditFinding[];
    summary?: Record<AuditSeverity, number>;
    score?: number;
    scored_findings?: number;
    engine?: string;
  };
  infrastructure: {
    docker_compose: Array<{
      file: string;
      services: Array<{
        name: string;
        image: string;
        ports: string[];
        depends_on: string[];
        restart: string;
      }>;
    }>;
    dockerfiles: Array<{
      path: string;
      base_images: string[];
      stages: string[];
      exposed_ports: string[];
    }>;
    ci: Array<{ path: string; name: string; triggers: string[]; jobs: string[] }>;
    makefile_targets: string[];
    env_files: Array<{ path: string; keys: string[]; gitignored: boolean; is_example: boolean }>;
    summary?: {
      compose_services: number;
      dockerfiles: number;
      ci_workflows: number;
      env_files: number;
      env_not_gitignored: string[];
      has_ci: boolean;
      has_containers: boolean;
    };
  };
  pipeline: {
    entrypoints: Array<{ path: string; kind: string }>;
    middleware: Array<{ file: string; line: number; snippet: string }>;
    core_layers: Array<{ path: string; name: string; description: string; files: number }>;
    summary?: { entrypoints: number; middleware: number; core_layers: number };
  };
  security: AuditFindingsSection;
  performance: AuditFindingsSection;
  notes: AuditNote[];
}

export interface BootstrapResponse {
  token: string;
  api_token: string;
  ws_path: string;
  ws_url?: string | null;
  expires_in: number;
  limits?: WebUIIngressLimits;
  model_name?: string | null;
  runtime_surface?: RuntimeSurface;
  runtime_capabilities?: RuntimeCapabilities;
}

export interface WebUITransportLimits {
  max_frame_bytes: number;
  envelope_reserve_bytes: number;
}

export interface WebUIMessageLimits {
  max_text_bytes: number;
}

export interface WebUIAttachmentLimits {
  max_count: number;
  max_file_bytes: number;
  max_total_bytes: number;
}

export interface WebUIIngressLimits {
  transport: WebUITransportLimits;
  message: WebUIMessageLimits;
  attachments: WebUIAttachmentLimits;
}

export type RuntimeSurface = "browser" | "native";
export type RestartBehavior = "none" | "nextTurn" | "engineRestart" | "appRestart";
export type SettingsApplyStatus =
  | "idle"
  | "pending"
  | "applying"
  | "restarting_engine"
  | "requires_app_restart";

export interface RuntimeCapabilities {
  can_restart_engine: boolean;
  can_pick_folder: boolean;
  can_open_logs: boolean;
  can_export_diagnostics: boolean;
}

export type MediaModelKind = "stt" | "tts" | "image" | "video" | "music";

export interface ProviderModelInfo {
  id: string;
  label?: string | null;
  description?: string | null;
  owned_by?: string | null;
  context_window?: number | null;
  /** Free-tier model (e.g. OpenRouter ":free" variants). */
  free?: boolean;
  /** Reads image input, as declared by the provider catalog when available. */
  vision?: boolean;
  output_modalities?: string[];
  media_modalities?: MediaModelKind[];
  voices?: string[];
  default_voice?: string;
}

export interface LiveVoiceSetup {
  ready: boolean;
  reason: string | null;
  missing: string[];
  mode: "navin" | "byok";
  settings_section: "voice";
  stt: { provider: string; model: string; configured: boolean; enabled: boolean };
  tts: { provider: string; model: string; configured: boolean; voice: string };
}

export interface ProviderModelsPayload {
  provider: string;
  label: string;
  status:
    | "available"
    | "unsupported"
    | "not_configured"
    | "missing_api_base"
    | "error";
  catalog_kind: "builtin" | "official" | "catalog" | "local" | "custom" | "unsupported";
  models: ProviderModelInfo[];
  model_count: number;
  message?: string | null;
  fetched_at?: number;
}

export interface OllamaRecommendedModel {
  id: string;
  label: string;
  description: string;
  size_hint: string;
  installed: boolean;
}

export interface OllamaSetupPayload {
  provider: "ollama";
  platform: "macos" | "linux" | "wsl" | "windows";
  phase: "install" | "start" | "configure" | "ready";
  binary?: string | null;
  binary_source?: string | null;
  /** True when the ollama CLI was found on PATH / common install paths. */
  binary_available?: boolean;
  installed: boolean;
  running: boolean;
  configured: boolean;
  api_base?: string | null;
  default_api_base: string;
  models: Array<{ id: string; size?: number | null; modified_at?: string | null }>;
  model_count: number;
  recommended_models: OllamaRecommendedModel[];
  install: {
    method: string;
    supported: boolean;
    command?: string | null;
    download_url: string;
    steps: string[];
  };
  /** Live install/pull progress published by the backend while an action runs. */
  active_job?: {
    action?: string;
    model?: string;
    status?: string;
    progress?: number | null;
    message?: string;
    detail?: string;
    started_at?: number;
    updated_at?: number;
  } | null;
  fetched_at?: number;
  settings?: SettingsPayload;
  last_action?: {
    ok: boolean;
    action: string;
    message: string;
    model?: string;
    preset?: string | null;
    api_base?: string;
    output?: string | null;
  };
}

/** Detect -> Install -> Start -> Configure state of the local OmniRoute gateway. */
export interface OmniRouteSetupPayload {
  provider: "omniroute";
  platform: "macos" | "linux" | "wsl" | "windows";
  phase: "install" | "start" | "configure" | "ready";
  binary?: string | null;
  binary_source?: string | null;
  installed: boolean;
  running: boolean;
  configured: boolean;
  api_base?: string | null;
  default_api_base: string;
  dashboard_url: string;
  /** Model id the wizard pins: the balanced ``auto`` combo. */
  default_model: string;
  combos: Array<{ id: string; label: string; description: string }>;
  /** Upstream models the auto combo currently routes across (public catalog). */
  models: ProviderModelInfo[];
  model_count: number;
  free_model_count: number;
  /** Name of an existing OmniRoute preset, if any, and whether it is the chat default. */
  preset?: string | null;
  active: boolean;
  install: {
    method: string;
    supported: boolean;
    command: string;
    start_command: string;
    node_version?: string | null;
    node_supported?: boolean | null;
    node_requirement: string;
    node_download_url: string;
    repo_url: string;
    site_url: string;
    steps: string[];
  };
  active_job?: {
    action?: string;
    status?: string;
    progress?: number | null;
    message?: string;
    detail?: string;
    started_at?: number;
    updated_at?: number;
  } | null;
  fetched_at?: number;
  settings?: SettingsPayload;
  last_action?: {
    ok: boolean;
    action: string;
    message: string;
    preset?: string | null;
    api_base?: string;
    output?: string | null;
  };
}

/** Progress of a browser sign-in started by the settings panel. */
export interface OAuthLoginState {
  provider: string;
  status: "pending" | "signed_in" | "error";
  authorize_url: string | null;
  awaiting_code: boolean;
  error: string | null;
}

export interface ComputerModelsPayload {
  provider: string;
  status: string;
  message: string | null;
  recommended: string | null;
  models: Array<{
    id: string;
    label: string;
    vision: boolean;
    grounding: boolean;
    preset: string;
    context_window: number | null;
  }>;
}

export interface ComputerDiagnostics {
  backend: string;
  backend_reason: string;
  notes: string[];
  enabled: boolean;
  passive?: boolean;
  ready: boolean;
  checks: Array<{ name: string; ok: boolean; detail: string; fix: string; optional?: boolean }>;
  screen: { width: number; height: number; left: number; top: number } | null;
  stopped: string | null;
}

export interface SettingsPayload {
  oauth?: OAuthLoginState;
  surface?: RuntimeSurface;
  runtime_surface?: RuntimeSurface;
  runtime_capabilities?: RuntimeCapabilities;
  apply_state?: {
    status: SettingsApplyStatus;
    sections: string[];
  };
  restart_behavior_by_section?: Record<string, RestartBehavior>;
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
    model_preset: string | null;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
    timezone: string;
    bot_name: string;
    bot_icon: string;
    tool_hint_max_length: number;
  };
  model_presets: Array<{
    name: string;
    label: string;
    active: boolean;
    is_default: boolean;
    model: string;
    provider: string;
    max_tokens: number;
    context_window_tokens: number;
    temperature: number;
    reasoning_effort: string | null;
    reasoning_effort_values?: string[];
    locked?: boolean;
    /** Tier alias used only for task routing; hidden from model lists. */
    routing_only?: boolean;
    source?: "managed" | "byok";
    /** False = hidden from chat picker; still listed in Settings. */
    enabled?: boolean;
    /** False when the managed catalog forbids this chat model at the current spend. */
    budget_allowed?: boolean;
    modality?: "text" | "image" | "video" | "audio" | "music" | "stt";
    vision?: boolean;
    grounding?: boolean;
    unit_price_usd?: number | null;
    price_note?: string | null;
    billing_unit?: string | null;
    billing_rate?: number | null;
  }>;
  /** Task-role routing: role slug (e.g. "deep", "search") → model preset name. */
  model_routes?: Record<string, string>;
  providers: Array<{
    name: string;
    label: string;
    configured: boolean;
    auth_type?: "api_key" | "oauth";
    api_key_required?: boolean;
    api_key_hint?: string | null;
    api_base?: string | null;
    default_api_base?: string | null;
    model_selectable?: boolean;
    model_catalog?: ProviderModelsPayload["catalog_kind"];
    api_type?: "auto" | "chat_completions" | "responses";
    /** Local / OpenAI-compatible private providers expose Auth None|Bearer. */
    supports_auth_mode?: boolean;
    auth_mode?: "none" | "bearer";
    oauth_account?: string | null;
    managed?: boolean;
    oauth_expires_at?: number | null;
    oauth_login_supported?: boolean;
    connection?: {
      regions: Array<{ id: string; label: string }>;
      plans: Array<{ id: string; label: string }>;
      protocols: Array<{ id: string; label: string }>;
      default_region: string;
      default_plan: string;
      default_protocol: string;
      bases: Record<string, string>;
      docs_url?: string | null;
      notes?: string | null;
    };
    endpoint_region?: string | null;
    access_plan?: string | null;
    wire_protocol?: string | null;
    resolved_api_base?: string | null;
  }>;
  web_search: {
    provider: string;
    api_key_hint?: string | null;
    base_url?: string | null;
    max_results: number;
    timeout: number;
    providers: Array<{
      name: string;
      label: string;
      credential: "none" | "api_key" | "optional_api_key" | "base_url";
    }>;
  };
  web: {
    enable: boolean;
    proxy?: string | null;
    user_agent?: string | null;
    search: {
      max_results: number;
      timeout: number;
    };
    fetch: {
      use_jina_reader: boolean;
    };
  };
  api?: {
    host: string;
    port: number;
    timeout: number;
    api_key_hint?: string | null;
  };
  /** Machine-wide kill-switches for board task git automation. */
  board_git?: {
    auto_branch_enabled: boolean;
    open_pr_enabled: boolean;
  };
  /** Per-host forge tokens: what makes Create PR work without the `gh` CLI. */
  forge?: {
    hosts: Array<{
      host: string;
      kind: ForgeKind;
      kind_pinned: boolean;
      token_hint?: string | null;
      token_configured: boolean;
    }>;
    /** Tokens found in the environment, read-only, names only. */
    env_tokens: Array<{ name: string }>;
    gh_available: boolean;
    kinds: ForgeKind[];
  };
  /** How the agent's browser runs. */
  browser?: {
    /** Hidden by default; a window is what makes a captcha solvable. */
    headless: boolean;
    live_view: boolean;
  };
  /** Desktop control (`computer` tool): screen, mouse and keyboard in any app. */
  computer?: {
    /** Enabled by default in Tauri and the CLI; explicit opt-outs are preserved. */
    enabled: boolean;
    ask: "never" | "destructive" | "always" | string;
    session_mode: "shared" | "dedicated" | string;
    live_view: boolean;
    audit_log: boolean;
    anthropic_native: boolean;
    protected_apps: string[];
    /** Model preset routed for desktop turns (Task routing > Desktop control). */
    route_preset: string;
    /** Kill-switch reason when `navin computer stop` is engaged, else null. */
    stopped: string | null;
    backend: string;
    backend_reason: string;
    backend_preference?: "auto" | "windows" | "macos" | "x11" | "wayland" | "none";
    backend_notes?: string[];
    display?: string;
    audit_screenshots?: boolean;
    settle_ms?: number;
    type_delay_ms?: number;
    max_actions_per_turn?: number;
    screenshot_max_width?: number;
    screenshot_max_height?: number;
    user_takeover_px?: number;
    failsafe_corner?: boolean;
    allowed_apps?: string[];
    blocked_apps?: string[];
    ask_apps?: string[];
    model?: string;
    model_vision?: boolean;
    model_grounding?: boolean;
    model_provider?: string | null;
  };
  observability?: {
    provider: "langfuse" | string;
    configured: boolean;
    base_url: string;
  };
  image_generation: {
    enabled: boolean;
    /** True while the flag is unset and follows the provider credential. */
    enabled_auto?: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    default_aspect_ratio: string;
    default_image_size: string;
    max_images_per_turn: number;
    save_dir: string;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      auth_type?: "api_key" | "oauth";
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
    }>;
    managed_models?: Array<{
      slug: string;
      name: string;
      unitPriceUsd?: number | null;
      priceNote?: string | null;
      isDefault?: boolean;
    }>;
    budget_caution?: string;
  };
  video_generation?: {
    enabled: boolean;
    /** True while the flag is unset and follows the provider credential. */
    enabled_auto?: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    default_aspect_ratio: string;
    default_duration_seconds: number;
    default_resolution: string;
    max_wait_seconds: number;
    save_dir: string;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      auth_type?: "api_key" | "oauth";
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
    }>;
    managed_models?: Array<{
      slug: string;
      name: string;
      unitPriceUsd?: number | null;
      priceNote?: string | null;
      billingUnit?: string | null;
      billingRate?: number | null;
      isDefault?: boolean;
    }>;
    budget_caution?: string;
  };
  music_generation?: {
    enabled: boolean;
    enabled_auto?: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    save_dir: string;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      auth_type?: "api_key" | "oauth";
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
    }>;
    managed_models?: Array<{
      slug: string;
      name: string;
      unitPriceUsd?: number | null;
      priceNote?: string | null;
      isDefault?: boolean;
    }>;
    budget_caution?: string;
  };
  transcription?: {
    enabled: boolean;
    provider: string;
    provider_configured: boolean;
    model: string;
    language: string | null;
    max_duration_sec: number;
    max_upload_mb: number;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
    }>;
    managed_models?: Array<{
      slug: string;
      name: string;
      unitPriceUsd?: number | null;
      priceNote?: string | null;
      isDefault?: boolean;
    }>;
    budget_caution?: string;
  };
  voice?: {
    tts_provider: string;
    tts_provider_configured: boolean;
    tts_model: string;
    voice: string;
    auto_speak: boolean;
    response_format: string;
    realtime_enabled: boolean | null;
    realtime_allowed: boolean;
    realtime_required_plans: string[];
    managed_defaults?: { stt_model: string; tts_model: string; voice: string };
    live?: LiveVoiceSetup;
    providers: Array<{
      name: string;
      label: string;
      configured: boolean;
      api_key_hint?: string | null;
      api_base?: string | null;
      default_api_base?: string | null;
    }>;
    managed_models?: Array<{
      slug: string;
      name: string;
      unitPriceUsd?: number | null;
      priceNote?: string | null;
      isDefault?: boolean;
      supportsReference?: boolean;
    }>;
    budget_caution?: string;
  };
  runtime: {
    config_path: string;
    workspace_path: string;
    gateway_host: string;
    gateway_port: number;
    heartbeat: {
      enabled: boolean;
      interval_s: number;
      keep_recent_messages: number;
    };
    dream: {
      schedule: string;
    };
    unified_session: boolean;
  };
  usage?: {
    days: Array<{
      date: string;
      prompt_tokens: number;
      completion_tokens: number;
      cached_tokens: number;
      total_tokens: number;
      provider_tokens?: number;
      estimated_tokens?: number;
      requests: number;
      provider_requests?: number;
      estimated_requests?: number;
      sources?: Record<
        "user" | "api" | "cron" | "dream" | "system" | string,
        {
          prompt_tokens: number;
          completion_tokens: number;
          cached_tokens: number;
          total_tokens: number;
          provider_tokens?: number;
          estimated_tokens?: number;
          requests: number;
          provider_requests?: number;
          estimated_requests?: number;
        }
      >;
      models?: Record<
        string,
        {
          prompt_tokens: number;
          completion_tokens: number;
          cached_tokens: number;
          total_tokens: number;
          provider_tokens?: number;
          estimated_tokens?: number;
          requests: number;
          provider_requests?: number;
          estimated_requests?: number;
        }
      >;
    }>;
    total_tokens: number;
    total_tokens_30d: number;
    total_tokens_365d: number;
    peak_day_tokens: number;
    current_streak_days: number;
    longest_streak_days: number;
    active_days_30d: number;
    requests_30d: number;
    /** Calendar month ``YYYY-MM`` in the agent timezone. */
    month?: string;
    models_month?: Array<{
      model: string;
      requests: number;
      prompt_tokens: number;
      completion_tokens: number;
      cached_tokens: number;
      total_tokens: number;
    }>;
    month_total?: {
      requests: number;
      prompt_tokens: number;
      completion_tokens: number;
      cached_tokens: number;
      total_tokens: number;
    };
    updated_at?: string | null;
  };
  advanced: {
    restrict_to_workspace: boolean;
    workspace_sandbox?: {
      restrict_to_workspace: boolean;
      workspace_root: string;
      level: "off" | "application" | "system" | string;
      enforced: boolean;
      provider: string;
      provider_label: string;
      summary: string;
    };
    ssrf_whitelist_count: number;
    webui_allow_local_service_access: boolean;
    allow_local_preview_access?: boolean;
    webui_default_access_mode: WebuiDefaultAccessMode;
    private_service_protection_enabled: boolean;
    mcp_server_count: number;
    exec_enabled: boolean;
    exec_sandbox?: string | null;
    exec_path_prepend_set: boolean;
    exec_path_append_set: boolean;
  };
  requires_restart: boolean;
  restart_required_sections?: Array<"runtime" | "browser" | "image" | "video">;
  version?: {
    current: string;
  };
  updates?: {
    enabled: boolean;
    autoCheck: boolean;
    channel: "stable" | "beta";
    configured: boolean;
    skippedVersion: string;
    /**
     * Present exactly once, on the first snapshot after an install restarted
     * the app: how that install actually turned out.
     */
    justInstalled?: {
      version: string;
      ok: boolean;
      /** What is running instead, when the install did not take. */
      currentVersion?: string;
    } | null;
  };
  docs?: {
    base_url: string;
    chat_apps_url: string;
  };
}

export interface ApiServicePayload {
  installed: boolean;
  running: boolean;
  managed: boolean;
  host: string;
  port: number;
  timeout: number;
  api_key_hint?: string | null;
  endpoint: string;
  command: string;
  log_path?: string | null;
  last_action?: "started" | "stopped" | string;
}

export interface AppPackageRef {
  manager: string;
  name?: string;
}

export interface AppCapability {
  type: "cli" | "mcp" | "skill" | string;
  entry_point?: string;
  package?: AppPackageRef;
  path?: string;
  transport?: string;
  command?: string;
  args?: string[];
  url?: string;
  fields?: Array<{
    name: string;
    target?: string;
    required?: boolean;
    secret?: boolean;
    env_var?: string | null;
  }>;
}

export interface AppPlan {
  supported: boolean;
  strategy?: string;
  managed_paths?: string[];
  verification?: string[];
}

export interface AppTrust {
  registry: string;
  level: string;
  review_status: string;
}

export interface AppManifest {
  schema: "agent-app.v1" | string;
  id: string;
  display_name: string;
  version?: string;
  description: string;
  category: string;
  source: string;
  logo_url?: string | null;
  brand_color?: string | null;
  docs_url?: string | null;
  capabilities: AppCapability[];
  install: AppPlan;
  remove: AppPlan;
  trust: AppTrust;
}

export interface CliAppInfo {
  name: string;
  display_name: string;
  category: string;
  description: string;
  requires: string;
  source: string;
  entry_point: string;
  install_supported: boolean;
  installed: boolean;
  available: boolean;
  status: "installed" | "missing" | "available" | "unsupported" | "not_installed" | string;
  logo_url?: string | null;
  brand_color?: string | null;
  skill_installed: boolean;
  manifest?: AppManifest;
}

export interface CliAppsPayload {
  apps: CliAppInfo[];
  installed_count: number;
  catalog_updated_at?: string | null;
  catalog_refresh_pending?: boolean;
  last_action?: {
    ok: boolean;
    message: string;
    installed?: boolean;
    removed?: boolean;
    output?: string | null;
    still_available?: boolean;
    verification?: string[];
    verification_failed?: string[];
  };
}

export interface NavinFeatureInfo {
  name: string;
  display_name: string;
  type: "channel" | "feature" | string;
  enabled: boolean;
  configured?: boolean;
  config_values?: Record<string, string>;
  configured_fields?: string[];
  installed: boolean;
  ready: boolean;
  status: "enabled" | "missing_dependency" | "not_enabled" | string;
  install_supported: boolean;
  requires_restart: boolean;
}


export interface NavinFeaturesPayload {
  features: NavinFeatureInfo[];
  enabled_count: number;
  requires_restart?: boolean;
  last_action?: {
    ok: boolean;
    message: string;
    enabled?: boolean;
  };
}

export type ChannelSetupStatus =
  | "connected"
  | "configured"
  | "needs_setup"
  | "invalid"
  | "unsupported"
  | string;

export type ChannelValidationCheckStatus = "pass" | "warn" | "fail" | "skipped" | string;

export interface ChannelValidationCheck {
  id: string;
  label: string;
  status: ChannelValidationCheckStatus;
  message?: string;
  action_url?: string;
}

export interface ChannelIdentity {
  name?: string;
  workspace?: string;
  account?: string;
  avatar_url?: string;
}

export interface ChannelValidationPayload {
  name: string;
  status: ChannelSetupStatus;
  checks: ChannelValidationCheck[];
  identity?: ChannelIdentity;
  missing_fields: string[];
  can_enable: boolean;
  requires_restart: boolean;
  checked_at?: string;
  message?: string;
}

export interface PairingRequestInfo {
  code: string;
  channel: string;
  sender_id: string;
  created_at_ms?: number | null;
  expires_at_ms?: number | null;
  expires_in_seconds?: number | null;
}

export interface PairingPayload {
  requests: PairingRequestInfo[];
  last_action?: {
    ok: boolean;
    action: "approve" | "deny" | string;
    message: string;
    code?: string;
    channel?: string;
    sender_id?: string;
  };
}

export interface McpPresetField {
  name: string;
  label: string;
  secret: boolean;
  required: boolean;
  configured: boolean;
  placeholder?: string;
  env_var?: string | null;
}

export interface McpPresetInfo {
  name: string;
  display_name: string;
  category: string;
  description: string;
  docs_url: string;
  transport: "stdio" | "streamableHttp" | "sse" | "oauth" | string;
  requires: string;
  note: string;
  install_supported: boolean;
  installed: boolean;
  configured: boolean;
  available: boolean;
  status: "not_installed" | "configured" | "missing_credentials" | "missing_dependency" | "coming_soon" | string;
  logo_url?: string | null;
  brand_color?: string | null;
  required_fields: McpPresetField[];
  connection_summary: string;
  tool_count?: number;
  tool_names?: string[];
  checked_at?: string | null;
  error?: string | null;
  enabled_tools?: string[];
  source?: "preset" | "custom" | string;
  modules?: string[];
  manifest?: AppManifest;
}

export interface McpPresetsPayload {
  presets: McpPresetInfo[];
  installed_count: number;
  requires_restart?: boolean;
  hot_reload?: {
    ok: boolean;
    message: string;
    added?: string[];
    changed?: string[];
    removed?: string[];
    retried?: string[];
    connected?: string[];
    configured?: string[];
    failed?: string[];
    tools_removed?: number;
    requires_restart?: boolean;
  };
  last_action?: {
    ok: boolean;
    message: string;
    installed?: boolean;
    removed?: boolean;
    managed_paths_removed?: string[];
    verification?: string[];
    verification_failed?: string[];
    tool_count?: number;
    tool_names?: string[];
    checked_at?: string | null;
    error?: string | null;
  };
}



export interface ChannelLoginPayload {
  name: string;
  status: "idle" | "starting" | "waiting_qr" | "connected" | "failed" | "cancelled" | string;
  qrDataUrl?: string | null;
  error?: string | null;
}

export interface ChannelConfigurePayload {
  name: string;
  saved: boolean;
  saved_keys?: string[];
  navin_features?: NavinFeaturesPayload;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
  modelPreset?: string | null;
  contextWindowTokens?: number;
  timezone?: string;
  botName?: string;
  botIcon?: string;
  reasoningEffort?: string;
  toolHintMaxLength?: number;
  boardAutoBranch?: boolean;
  boardOpenPr?: boolean;
  browserHeadless?: boolean;
  browserLiveView?: boolean;
  computerEnabled?: boolean;
  computerAsk?: "never" | "destructive" | "always";
  computerSessionMode?: "shared" | "dedicated";
  computerLiveView?: boolean;
  computerAuditLog?: boolean;
  computerAnthropicNative?: boolean;
  computerBackend?: "auto" | "windows" | "macos" | "x11" | "wayland" | "none";
  computerDisplay?: string;
  computerAuditScreenshots?: boolean;
  computerSettleMs?: number;
  computerTypeDelayMs?: number;
  computerMaxActionsPerTurn?: number;
  computerScreenshotMaxWidth?: number;
  computerScreenshotMaxHeight?: number;
  computerUserTakeoverPx?: number;
  computerFailsafeCorner?: boolean;
  computerProtectedApps?: string[];
  computerAllowedApps?: string[];
  computerBlockedApps?: string[];
  computerAskApps?: string[];
  /** Forge token entry to add, update or remove (Settings > Git). */
  forgeHost?: string;
  /** Empty string clears the stored token for `forgeHost`. */
  forgeToken?: string;
  /** "auto" unpins the host so detection runs again. */
  forgeKind?: ForgeKind | "auto";
  forgeRemove?: boolean;
}

export interface ModelConfigurationCreate {
  name?: string;
  label: string;
  provider: string;
  model: string;
}

export interface ModelConfigurationImportEntry {
  id: string;
  label?: string;
  context_window?: number | null;
}

export interface ModelConfigurationImportResult {
  provider: string;
  imported: number;
  skipped: number;
}

export interface ModelConfigurationUpdate {
  name: string;
  label?: string;
  provider?: string;
  model?: string;
  contextWindowTokens?: number;
  reasoningEffort?: string;
  /** Hide from chat picker without deleting the preset. */
  enabled?: boolean;
}

export interface ProviderSettingsUpdate {
  provider: string;
  apiKey?: string;
  apiBase?: string;
  apiType?: "auto" | "chat_completions" | "responses";
  authMode?: "none" | "bearer";
  endpointRegion?: string;
  accessPlan?: string;
  wireProtocol?: string;
}

export interface ProviderConnectionTestPayload {
  ok: boolean;
  provider: string;
  label: string;
  status: "available" | "unsupported" | "not_configured" | "missing_api_base" | "error";
  message?: string | null;
  api_base?: string | null;
  models: Array<{ id: string; label?: string | null }>;
  model_count: number;
  capabilities: string[];
  quota?: Record<string, unknown> | null;
  latency_ms: number;
}

export interface WebSearchSettingsUpdate {
  provider: string;
  apiKey?: string;
  baseUrl?: string;
  maxResults?: number;
  timeout?: number;
  useJinaReader?: boolean;
}

export interface NetworkSafetySettingsUpdate {
  webuiAllowLocalServiceAccess: boolean;
  webuiDefaultAccessMode: WebuiDefaultAccessMode;
}

export interface ImageGenerationSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
  defaultAspectRatio: string;
  defaultImageSize: string;
  maxImagesPerTurn: number;
}

export interface VideoGenerationSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
  defaultAspectRatio: string;
  defaultDurationSeconds: number;
  defaultResolution: string;
}

export interface MusicGenerationSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
}

export interface TranscriptionSettingsUpdate {
  enabled: boolean;
  provider: string;
  model: string;
  language: string;
  maxDurationSec: number;
  maxUploadMb: number;
}

export interface VoiceSettingsUpdate {
  ttsProvider: string;
  ttsModel: string;
  voice: string;
  autoSpeak: boolean;
  responseFormat: string;
  /** null = follow plan gate (Pro+/Team); true/false force. */
  realtimeEnabled: boolean | null;
}

/**
 * Backend-owned contract for how a slash command affects WebUI turn state.
 *
 * - side_channel: returns control text without starting or ending an agent turn.
 * - finalize_active_turn: side-channel command that also closes the active UI turn.
 * - stop_active_turn: cancels the active turn; exact submits may be intercepted locally.
 * - agent_turn: always enters the normal agent path.
 * - agent_turn_with_args: no args is side-channel usage; args enter the agent path.
 */
export type SlashCommandLifecycle =
  | "side_channel"
  | "finalize_active_turn"
  | "stop_active_turn"
  | "agent_turn"
  | "agent_turn_with_args";

export interface SlashCommand {
  command: string;
  title: string;
  description: string;
  icon: string;
  argHint?: string;
  lifecycle: SlashCommandLifecycle;
  acceptsArgs: boolean;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

export interface InboundTurnMetadata {
  turn_id?: string;
  turn_phase?: UITurnPhase;
  turn_seq?: number;
  model_name?: string;
  model_label?: string;
  task_role?: string;
}

export type PresenceMember = {
  member_id: string;
  display_name: string;
  role: string;
};

export type InboundEvent =
  | {
      event: "ready";
      chat_id: string;
      client_id: string;
      org_role?: string;
      display_name?: string;
    }
  | { event: "attached"; chat_id: string }
  | {
      event: "presence_sync";
      chat_id: string;
      members: PresenceMember[];
    }
  | {
      event: "presence_join";
      chat_id: string;
      member: PresenceMember;
    }
  | {
      event: "presence_leave";
      chat_id: string;
      member: PresenceMember;
    }
  | {
      event: "member_cursor";
      chat_id: string;
      member_id?: string;
      display_name?: string;
      cursor?: Record<string, unknown>;
    }
  /** navin.live account changed gateway-side (sign-in handoff, plan change,
   * sign-out): consumers should refetch `/api/webui/account`. */
  | { event: "account_updated" }
  | ({
      event: "message";
      chat_id: string;
      text: string;
      reply_to?: string;
      media?: string[];
      media_urls?: Array<{ url: string; name?: string }>;
      tool_events?: ToolProgressEvent[];
      /** Present when the frame is an agent breadcrumb (e.g. tool hint,
       * generic progress line) rather than a conversational reply. */
      kind?: "tool_hint" | "progress" | "reasoning";
      /** Server-measured turn wall time when this frame finishes an assistant reply. */
      latency_ms?: number;
      /** Model that produced this assistant frame. */
      model_name?: string;
      model_label?: string;
      model_preset?: string;
      task_role?: string;
      /** Lightweight provenance for proactive assistant messages. */
      source?: UIMessageSource;
      /** Optional structured payload on progress frames (channel-specific). */
      agent_ui?: AgentUIBlob;
    } & InboundTurnMetadata)
  | ({
      event: "file_edit";
      chat_id: string;
      edits: UIFileEdit[];
    } & InboundTurnMetadata)
  | {
      /** Coalesced gateway watcher signal: files changed on disk under root. */
      event: "fs_changed";
      chat_id: string;
      root: string;
    }
  | ({
      event: "delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    } & InboundTurnMetadata)
  | ({
      event: "stream_end";
      chat_id: string;
      stream_id?: string;
      text?: string;
    } & InboundTurnMetadata)
  | ({
      event: "reasoning_delta";
      chat_id: string;
      text: string;
      stream_id?: string;
    } & InboundTurnMetadata)
  | ({
      event: "reasoning_end";
      chat_id: string;
      stream_id?: string;
    } & InboundTurnMetadata)
  | {
      event: "runtime_model_updated";
      model_name: string;
      model_preset?: string | null;
      reason?: string | null;
      previous_model?: string | null;
      used_percent?: number | null;
    }
  | ({
      event: "turn_end";
      chat_id: string;
      latency_ms?: number;
      /** Wall time per agent turn phase (restore/build/run/save...), in ms. */
      phase_timings_ms?: Record<string, number>;
      /** Model that finished this turn (keeps history labels stable). */
      model_name?: string;
      model_label?: string;
      model_preset?: string;
      task_role?: string;
      /** Authoritative sustained-goal snapshot for this chat (same shape as ``goal_state`` events). */
      goal_state?: GoalStateWsPayload;
    } & InboundTurnMetadata)
  | {
      event: "goal_status";
      chat_id: string;
      /** Turn executing (user message through agent loop). */
      status: "running" | "idle";
      /** Server ``time.time()`` when ``status`` is ``running``. */
      started_at?: number;
    }
  | {
      event: "goal_state";
      chat_id: string;
      goal_state: GoalStateWsPayload;
    }
  | {
      event: "session_updated";
      chat_id: string;
      scope?: "metadata" | "thread" | string;
      workspace_scope?: WorkspaceScopePayload;
    }
  | { event: "board_updated"; project_path?: string }
  | {
      event: "montage_updated";
      project_path?: string;
      kind?: "timeline" | "job" | "assets" | string;
      name?: string;
      job?: import("./api").MontageJobSummary;
    }
  | {
      event: "metagraph_updated";
      project_path?: string;
      generation?: number;
      view?: string;
      diff?: MetagraphDiff;
    }
  | {
      event: "notification";
      chat_id?: string;
      title: string;
      detail?: string;
      level?: "info" | "success" | "warning" | "error" | string;
      source?: string;
      key?: string;
    }
  | {
      event: "context_compacted";
      chat_id: string;
      /** "consolidation" = token pressure mid-conversation, "idle" = auto-compact. */
      kind: "consolidation" | "idle" | string;
      messages_archived?: number;
      tokens_before?: number;
      tokens_after?: number;
    }
  | {
      /** A restore point (conversation + code) was snapshotted for this turn. */
      event: "checkpoint_saved";
      chat_id: string;
      name: string;
      auto?: boolean;
    }
  | {
      /** A tool has suspended itself and is waiting for an answer. */
      event: "approval_request";
      chat_id: string;
      request_id: string;
      tool: string;
      action: string;
      reason: string;
      detail?: string;
      consequence?: string;
      scope?: string;
      remember_offered?: boolean;
      /** Epoch ms after which the backend refuses by itself. */
      expires_at_ms?: number | null;
    }
  | {
      /** A pending request is settled, however it ended. */
      event: "approval_closed";
      chat_id: string;
      request_id: string;
      allowed: boolean;
      reason?: string;
    }
  | {
      /** The agent paused on a product fork and is waiting for a pick. */
      event: "choice_request";
      chat_id: string;
      request_id: string;
      question: string;
      options: Array<{
        id: string;
        label: string;
        detail?: string;
        recommended?: boolean;
      }>;
      allow_skip?: boolean;
      recommended_id?: string;
      expires_at_ms?: number | null;
    }
  | {
      event: "choice_closed";
      chat_id: string;
      request_id: string;
      option_id?: string;
      skipped?: boolean;
    }
  | {
      event: "terminal_open_request";
      chat_id?: string;
      shell?: string;
      cwd?: string;
    }
  | {
      /** Live feed of an agent exec command (read-only terminal tabs). */
      event: "agent_exec";
      chat_id?: string;
      id?: string;
      phase?: string;
      command?: string;
      cwd?: string;
      background?: boolean;
      data?: string;
      exit_code?: number;
    }
  | {
      /** Live mirror of the agent's headless browser (screencast frames). */
      event: "agent_browser";
      chat_id?: string;
      id?: string;
      phase?: string;
      url?: string;
      title?: string;
      action?: string;
      data?: string;
      width?: number;
      height?: number;
      user_control?: boolean;
    }
  | {
      event: "agent_browser_input_done" | "agent_browser_closed" | "agent_browser_error";
      chat_id?: string;
      id?: string;
      request_id?: string;
      user_control?: boolean;
      url?: string;
      closed?: boolean;
      detail?: string;
    }
  | {
      event: "editor_open_request";
      chat_id?: string;
      path?: string;
      kind?: string;
      line?: number;
    }
  | {
      event: "composer_mode_request";
      chat_id?: string;
      mode?: string;
    }
  | {
      /** Open a product module surface (Code workbench, …) for this turn. */
      event: "product_module_request";
      chat_id?: string;
      module?: string;
    }
  | {
      /** Live parallel subagent card (spawn fan-out). */
      event: "subagent_progress";
      chat_id?: string;
      task_id: string;
      label: string;
      phase: string;
      status_line: string;
      model?: string;
      iteration?: number;
      done?: boolean;
      error?: string;
      task_description?: string;
    }
  | {
      event: "preview_open_request";
      chat_id?: string;
      kind?: "web" | "mobile" | string;
      url?: string;
    }
  | {
      event: "file_preview_open_request";
      chat_id?: string;
      path?: string;
    }
  | {
      event: "artifact_upsert";
      chat_id?: string;
      artifact?: ArtifactRecord;
    }
  | {
      event: "artifact_select";
      chat_id?: string;
      artifact_id?: string;
    }
  | { event: "terminal_shells"; shells: TerminalShellInfo[] }
  | { event: "terminal_opened"; terminal_id: string; shell?: string; cwd?: string }
  | { event: "terminal_output"; terminal_id: string; data: string }
  | { event: "terminal_exit"; terminal_id: string; exit_code?: number | null }
  | { event: "terminal_error"; terminal_id?: string; detail?: string }
  | { event: "assist_delta"; request_id: string; text?: string }
  | {
      event: "assist_done";
      request_id: string;
      completion?: string;
      replacement?: string;
      model?: string;
      reason?: string;
      cancelled?: boolean;
      route?: string;
      latency_ms?: number;
      ttft_ms?: number;
    }
  | { event: "assist_error"; request_id?: string; detail?: string; status?: number }
  | {
      event: "mobile_preview_opened";
      preview_id: string;
      serial?: string | null;
      backend?: string;
    }
  | {
      event: "mobile_preview_frame";
      preview_id: string;
      png_b64?: string;
      width?: number;
      height?: number;
      seq?: number;
      ts_ms?: number;
      fps?: number;
      mem_mb?: number;
      cpu_pct?: number;
      error?: string;
    }
  | {
      event: "mobile_preview_logs";
      preview_id: string;
      lines?: string[];
    }
  | {
      event: "mobile_preview_ui_dump";
      preview_id: string;
      xml?: string;
    }
  | {
      event: "mobile_preview_error";
      preview_id?: string;
      detail?: string;
    }
  | { event: "mobile_preview_exit"; preview_id: string }
  | {
      event: "mobile_preview_status";
      ready?: boolean;
      adb?: string | null;
      sdk?: string | null;
      source?: string | null;
      devices?: string[];
      avds?: string[];
      error?: string | null;
      help?: string | null;
      fixes?: MobilePreviewFix[];
    }
  | { event: "mobile_preview_avd_started"; ok?: boolean; detail?: string | null }
  | { event: "transcription_result"; request_id: string; text: string }
  | {
      event: "transcription_error";
      request_id?: string;
      detail?: string;
      provider?: string;
    }
  | {
      event: "voice_session_started";
      session_id: string;
      request_id?: string;
      auto_speak?: boolean;
      tts_provider?: string;
      tts_configured?: boolean;
      voice?: string;
    }
  | {
      event: "voice_session_ended";
      session_id: string;
      request_id?: string;
    }
  | {
      event: "transcript_partial";
      session_id: string;
      text: string;
      final?: boolean;
      request_id?: string;
    }
  | {
      /** Live conversation: the spoken transcript rewritten as the chat prompt. */
      event: "voice_prompt_ready";
      session_id: string;
      text: string;
      raw_text: string;
      rewritten?: boolean;
      request_id?: string;
    }
  | {
      event: "tts_audio";
      session_id: string;
      audio_base64: string;
      mime?: string;
      request_id?: string;
    }
  | {
      event: "tts_cancelled";
      session_id: string;
      request_id?: string;
    }
  | {
      event: "voice_session_error";
      detail?: string;
      session_id?: string;
      request_id?: string;
      provider?: string;
      required_plans?: string[];
    }
  | {
      event: "error";
      chat_id?: string;
      detail?: string;
      reason?: string;
    };

/** Base64-encoded file attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must use a server-whitelisted image, video, or document MIME
 * type. SVG remains rejected on ingress to avoid an embedded-script XSS
 * surface. ``name`` is advisory and is surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export interface OutboundCliAppMention {
  name: string;
  display_name?: string;
  category?: string;
  entry_point?: string;
  logo_url?: string | null;
  brand_color?: string | null;
}

export interface OutboundMcpPresetMention {
  name: string;
  display_name?: string;
  category?: string;
  transport?: string;
  status?: string;
  configured?: boolean;
  logo_url?: string | null;
  brand_color?: string | null;
}

/** A workspace path the user attached with `@path`, scoping the turn. */
export interface OutboundFileMention {
  path: string;
  kind: "file" | "directory" | "symbol";
  /** Identifier for a symbol mention; the file's own name is derived server-side. */
  name?: string;
  /** 1-based definition line for a symbol mention. */
  line?: number;
}

/** Response shape for ``GET .../webui-thread`` (server-built transcript replay). */
export interface WebuiThreadPagePayload {
  before_cursor?: string | null;
  has_more_before?: boolean;
  loaded_message_count?: number;
  total_known_message_count?: number;
  user_message_offset?: number;
}

export interface WebuiThreadPersistedPayload {
  schemaVersion: number;
  sessionKey?: string;
  savedAt?: string;
  messages: UIMessage[];
  fork_boundary_message_count?: number;
  has_pending_tool_calls?: boolean;
  page?: WebuiThreadPagePayload;
  workspace_scope?: WorkspaceScopePayload;
}

export type FilePreviewKind =
  | "text"
  | "image"
  | "binary"
  | "audio"
  | "video"
  | "pdf"
  | "office"
  | "spreadsheet"
  | "csv"
  | "html"
  | "markdown"
  | "json"
  | "xml"
  | "yaml";

/** One worksheet of an Excel file, as text cells for the table viewer. */
export interface SpreadsheetSheetPayload {
  name: string;
  rows: string[][];
  /** More rows or columns exist than the gateway sends. */
  truncated?: boolean;
  hidden?: boolean;
}

/** Artifact shown in the chat-side Artifact Canvas (HTML / MD / Mermaid / file). */
export type ArtifactType = "html" | "markdown" | "mermaid" | "file";

export interface ArtifactRecord {
  id: string;
  chat_id?: string;
  type: ArtifactType | string;
  title: string;
  content?: string;
  version?: number;
  created_at?: string;
  updated_at?: string;
  source_path?: string | null;
  content_file?: string;
}

export interface FilePreviewPayload {
  path: string;
  display_path: string;
  project_path: string;
  language: string;
  content: string;
  size: number;
  truncated: boolean;
  kind?: FilePreviewKind;
  data_url?: string;
  name?: string;
  mime?: string;
  /** Office files: whether the gateway can render them to PDF (LibreOffice). */
  render_available?: boolean;
  /** Office files: how to install the renderer when it is missing. */
  render_hint?: string;
  /** kind=spreadsheet: worksheets read natively by the gateway (no LibreOffice). */
  sheets?: SpreadsheetSheetPayload[];
}

export interface FileSavePayload {
  path: string;
  display_path: string;
  size: number;
  saved: boolean;
}

export interface FileCreatePayload {
  path: string;
  display_path: string;
  kind: "file" | "directory";
  created: boolean;
}

export interface FileDeletePayload {
  path: string;
  display_path: string;
  kind: "file" | "directory";
  deleted: boolean;
}

export interface FileRenamePayload {
  path: string;
  display_path: string;
  previous_path?: string;
  renamed: boolean;
}

export interface FilePastePayload {
  path: string;
  display_path: string;
  kind: "file" | "directory";
  /** Set only for a move, so callers know which path stopped existing. */
  previous_path?: string | null;
  pasted: boolean;
}

export interface FileTreeEntry {
  name: string;
  path: string;
  type: "dir" | "file";
  size: number;
  heavy?: boolean;
}

export interface FileTreePayload {
  path: string;
  display_path: string;
  project_path: string;
  entries: FileTreeEntry[];
  truncated: boolean;
}

export interface TerminalShellInfo {
  name: string;
  path: string;
  default: boolean;
  kind?: string;
}

export interface TerminalEvent {
  event: "terminal_opened" | "terminal_output" | "terminal_exit" | "terminal_error";
  terminal_id: string;
  shell?: string;
  cwd?: string;
  data?: string;
  exit_code?: number | null;
  detail?: string;
  /** On terminal_opened: the shell actually runs inside the OS sandbox. */
  sandbox?: boolean;
}

export interface MobilePreviewFix {
  id: string;
  label: string;
  command?: string;
  prompt?: string;
}

export interface MobileGuideStep {
  id: number;
  key: string;
  title: string;
  body: string;
  status: "done" | "current" | "todo";
  primary_action?: string | null;
  primary_label?: string | null;
  secondary_action?: string | null;
  secondary_label?: string | null;
  link?: string | null;
  link_label?: string | null;
}

export interface MobileGuide {
  current_step: number;
  headline: string;
  subtitle: string;
  steps: MobileGuideStep[];
}

export interface MobilePreviewIosChainStep {
  id: string;
  title: string;
  ok: boolean;
  required?: boolean;
  detail?: string;
  command?: string;
  verify?: string;
  role?: string;
}

export interface MobilePreviewIosStatus {
  available?: boolean;
  supported?: boolean;
  ready?: boolean;
  platform?: string | null;
  reason?: string | null;
  help?: string | null;
  error?: string | null;
  xcode?: boolean;
  simctl?: boolean;
  idevice?: boolean;
  idb?: boolean;
  brew?: boolean;
  devices?: string[];
  simulators?: Array<{ udid: string; name: string; state: string }>;
  usb_devices?: string[];
  /** Ordered install/verify chain for iOS on this host. */
  chain?: MobilePreviewIosChainStep[];
  fixes?: MobilePreviewFix[];
}

export interface MobilePreviewStatus {
  ready: boolean;
  platform?: string | null;
  /** Stacks available on this host, e.g. ["android"] or ["android","ios"]. */
  stacks?: string[];
  adb?: string | null;
  sdk?: string | null;
  source?: string | null;
  devices: string[];
  /** Plugged phones not usable yet (unauthorized RSA prompt, offline...). */
  pending_devices?: string[];
  avds: string[];
  error?: string | null;
  help?: string | null;
  fixes: MobilePreviewFix[];
  can_auto_install?: boolean;
  acceleration_ok?: boolean;
  acceleration_detail?: string | null;
  stable?: boolean;
  block_local_emulator?: boolean;
  recommendations?: string[];
  guide?: MobileGuide | null;
  ios?: MobilePreviewIosStatus | null;
  install_attempt?: {
    ok?: boolean;
    already?: boolean;
    adb?: string;
    detail?: string;
    help?: string;
    log?: string;
  } | null;
}

export type MobilePreviewEvent =
  | {
      event: "mobile_preview_opened";
      preview_id: string;
      serial?: string | null;
      backend?: string;
    }
  | {
      event: "mobile_preview_frame";
      preview_id: string;
      png_b64?: string;
      width?: number;
      height?: number;
      seq?: number;
      ts_ms?: number;
      fps?: number;
      mem_mb?: number;
      cpu_pct?: number;
      error?: string;
    }
  | {
      event: "mobile_preview_logs";
      preview_id: string;
      lines?: string[];
    }
  | {
      event: "mobile_preview_ui_dump";
      preview_id: string;
      xml?: string;
    }
  | {
      event: "mobile_preview_error";
      preview_id?: string;
      detail?: string;
    }
  | {
      event: "mobile_preview_exit";
      preview_id: string;
    }
  | ({
      event: "mobile_preview_status";
    } & MobilePreviewStatus);

export type Outbound =
  | { type: "new_chat"; workspace_scope?: WorkspaceScopePayload }
  | { type: "fork_chat"; source_chat_id: string; before_user_index: number; title?: string }
  | { type: "attach"; chat_id: string }
  | { type: "set_workspace_scope"; chat_id: string; workspace_scope: WorkspaceScopePayload }
  | { type: "transcribe_audio"; request_id: string; data_url: string; duration_ms?: number }
  | {
      type: "voice_session_start";
      request_id: string;
      session_id?: string;
    }
  | {
      type: "voice_audio_chunk";
      request_id: string;
      session_id: string;
      data_url?: string;
      duration_ms?: number;
      final?: boolean;
      speak_text?: string;
      barge_in?: boolean;
      cancel_tts?: boolean;
    }
  | {
      type: "voice_prompt";
      request_id: string;
      session_id: string;
      text: string;
      context?: string;
    }
  | {
      type: "voice_session_end";
      request_id: string;
      session_id: string;
      speak_text?: string;
      barge_in?: boolean;
      cancel_tts?: boolean;
    }
  | { type: "approval_decision"; request_id: string; allowed: boolean; remember: boolean }
  | { type: "choice_answer"; request_id: string; option_id?: string; skipped?: boolean; custom_text?: string }
  | { type: "terminal_shells" }
  | {
      type: "terminal_open";
      terminal_id: string;
      shell?: string;
      chat_id?: string;
      cols?: number;
      rows?: number;
      cwd?: string;
      /** Isolated terminal: start the shell inside the agent's OS sandbox. */
      sandbox?: boolean;
    }
  | { type: "terminal_input"; terminal_id: string; data: string }
  | { type: "terminal_resize"; terminal_id: string; cols: number; rows: number }
  | { type: "terminal_close"; terminal_id: string }
  | {
      type: "mobile_preview_open";
      preview_id: string;
      serial?: string;
      fps?: number;
    }
  | { type: "mobile_preview_close"; preview_id: string }
  | { type: "mobile_preview_status"; install?: boolean }
  | { type: "mobile_preview_start_avd"; avd: string }
  | { type: "mobile_preview_tap"; preview_id: string; x: number; y: number }
  | {
      type: "mobile_preview_swipe";
      preview_id: string;
      x1: number;
      y1: number;
      x2: number;
      y2: number;
      duration_ms?: number;
    }
  | { type: "mobile_preview_key"; preview_id: string; keycode: string }
  | { type: "mobile_preview_text"; preview_id: string; text: string }
  | { type: "mobile_preview_ui_dump"; preview_id: string }
  | {
      /** A click or keystroke the user made on the mirror of the agent's browser. */
      type: "agent_browser_input";
      chat_id: string;
      id?: string;
      request_id?: string;
      action: "click" | "move" | "scroll" | "text" | "key" | "takeover" | "release";
      /** Point on the streamed frame, in that frame's own pixels. */
      x?: number;
      y?: number;
      /** Size of the frame the point was measured against. */
      width?: number;
      height?: number;
      dx?: number;
      dy?: number;
      text?: string;
      key?: string;
      count?: number;
      button?: "left" | "right" | "middle";
    }
  | { type: "agent_browser_close"; chat_id: string; id?: string; request_id?: string }
  | {
      type: "assist_complete";
      request_id: string;
      path: string;
      prefix: string;
      suffix: string;
      language?: string;
    }
  | {
      type: "assist_edit";
      request_id: string;
      path: string;
      selection: string;
      instruction: string;
      prefix?: string;
      suffix?: string;
      language?: string;
    }
  | { type: "assist_cancel"; request_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      cli_apps?: OutboundCliAppMention[];
      mcp_presets?: OutboundMcpPresetMention[];
      file_mentions?: OutboundFileMention[];
      document_template?: { category: string; name: string };
      media_template?: { id: string; title?: string };
      media_templates?: { id: string; title?: string }[];
      workspace_scope?: WorkspaceScopePayload;
      turn_id?: string;
      /** Model preset pinned to this conversation; shapes this turn only and
       * leaves the global default untouched. */
      model_preset?: string;
      /** Product shell module (code, seo, …) for tool/skill scoping. */
      product_module?: string;
      /** Open editor tabs from the Code workbench (agent context pack). */
      open_files?: string[];
      /** Sent from the live voice conversation: the reply is read aloud, so
       * the agent talks like a colleague on a call. */
      voice_mode?: true;
      /** Marks messages sent by the embedded WebUI, without changing the
       * generic websocket protocol for other clients. */
      webui?: true;
    };
