#!/bin/sh
set -eu

package="navin-ai"
main_source="https://github.com/EIAGEN/navin-claw/archive/refs/heads/main.zip"
install_target="$package"
install_source="PyPI"
dry_run="0"
navin_runner=""
navin_python=""

info() {
  printf '%s\n' "$*"
}

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

install_failure_hint() {
  printf '%s\n' "Error: could not install navin from $install_source." >&2
  printf '%s\n' "If pip mentioned externally-managed-environment, use uv, pipx, or a virtual environment instead of system pip." >&2
  printf '%s\n' "You can also run manually:" >&2
  printf '  %s\n' "uv tool install --force --upgrade $install_target" >&2
  printf '  %s\n' "$python_bin -m venv ~/.navin/venv" >&2
  printf '  %s\n' "~/.navin/venv/bin/python -m pip install --upgrade $install_target" >&2
  printf '%s\n' "Then start Navin with:" >&2
  printf '  %s\n' "navin webui" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage: install.sh [--dev] [--dry-run]

By default this installs or upgrades navin-ai from PyPI.
Use --dev to install from the current main branch on GitHub.
Use --dry-run to print what would happen without installing anything.
EOF
}

find_python() {
  for candidate in python3 python; do
    if command -v "$candidate" >/dev/null 2>&1; then
      if "$candidate" - <<'PY' >/dev/null 2>&1
import sys
raise SystemExit(0 if sys.version_info >= (3, 11) else 1)
PY
      then
        printf '%s\n' "$candidate"
        return 0
      fi
    fi
  done
  return 1
}

python_is_virtual_env() {
  "$python_bin" - <<'PY'
import sys
raise SystemExit(0 if sys.prefix != sys.base_prefix else 1)
PY
}

ensure_pip() {
  target_python="$1"
  if "$target_python" -m pip --version >/dev/null 2>&1; then
    return 0
  fi

  info "pip was not found for $target_python. Trying ensurepip..."
  "$target_python" -m ensurepip --upgrade >/dev/null 2>&1
}

run_navin() {
  case "$navin_runner" in
    uv)
      uv tool run --from "$install_target" navin "$@"
      ;;
    pipx)
      pipx run --spec "$install_target" navin "$@"
      ;;
    python)
      "$navin_python" -m navin "$@"
      ;;
    *)
      fail "navin was installed, but no runner was configured"
      ;;
  esac
}

navin_try_command() {
  case "$navin_runner" in
    uv)
      printf '%s\n' "uv tool run --from $install_target navin"
      ;;
    pipx)
      printf '%s\n' "pipx run --spec $install_target navin"
      ;;
    python)
      printf '%s\n' "$navin_python -m navin"
      ;;
  esac
}

install_with_active_python() {
  info "Detected an active virtual environment. Installing into it..."
  ensure_pip "$python_bin" || return 1
  "$python_bin" -m pip install --upgrade "$install_target" || return 1
  navin_runner="python"
  navin_python="$python_bin"
}

install_with_uv() {
  info "Installing or upgrading navin from $install_source with uv tool..."
  uv tool install --python "$python_bin" --force --upgrade "$install_target" || return 1
  navin_runner="uv"
}

install_with_pipx() {
  info "Installing or upgrading navin from $install_source with pipx..."
  pipx install --python "$python_bin" --force "$install_target" || return 1
  navin_runner="pipx"
}

write_managed_wrapper() {
  bin_dir="${NAVIN_BIN_DIR:-$HOME/.local/bin}"
  wrapper="$bin_dir/navin"
  mkdir -p "$bin_dir" || return 0

  if [ -e "$wrapper" ] && ! grep -q "Generated by navin installer" "$wrapper" 2>/dev/null; then
    info "Not updating $wrapper because it already exists."
    return 0
  fi

  cat > "$wrapper" <<EOF
#!/bin/sh
# Generated by navin installer.
exec "$navin_python" -m navin "\$@"
EOF
  chmod +x "$wrapper" || return 0

  if ! command -v navin >/dev/null 2>&1; then
    info "Installed a navin launcher at $wrapper."
    info "Add $bin_dir to PATH to run navin directly."
  fi
}

install_with_managed_venv() {
  [ -n "${HOME:-}" ] || fail "HOME is not set; cannot create a managed virtual environment"

  venv_dir="${NAVIN_VENV:-$HOME/.navin/venv}"
  venv_python="$venv_dir/bin/python"

  if [ ! -x "$venv_python" ]; then
    info "Creating a dedicated virtual environment at $venv_dir..."
    mkdir -p "$(dirname "$venv_dir")"
    "$python_bin" -m venv "$venv_dir" || return 1
  fi

  "$venv_python" - <<'PY' >/dev/null 2>&1 || fail "The managed venv uses Python older than 3.11. Remove it or set NAVIN_VENV to a new path."
import sys
raise SystemExit(0 if sys.version_info >= (3, 11) else 1)
PY

  info "Installing or upgrading navin from $install_source in $venv_dir..."
  ensure_pip "$venv_python" || return 1
  "$venv_python" -m pip install --upgrade "$install_target" || return 1

  navin_runner="python"
  navin_python="$venv_python"
  write_managed_wrapper
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dev)
      install_target="$main_source"
      install_source="GitHub main"
      ;;
    --dry-run)
      dry_run="1"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "Unknown option: $1"
      ;;
  esac
  shift
done

python_bin="${PYTHON:-}"

if [ -n "$python_bin" ]; then
  command -v "$python_bin" >/dev/null 2>&1 || fail "PYTHON=$python_bin was not found"
  "$python_bin" - <<'PY' >/dev/null 2>&1 || fail "navin requires Python 3.11 or newer"
import sys
raise SystemExit(0 if sys.version_info >= (3, 11) else 1)
PY
else
  python_bin="$(find_python)" || fail "Python 3.11 or newer was not found. Install Python first, then rerun this command."
fi

info "Using Python: $("$python_bin" --version 2>&1)"

if [ "$dry_run" = "1" ]; then
  info "Dry run: would install or upgrade navin from $install_source."
  if python_is_virtual_env; then
    info "Dry run: active virtual environment detected; would run: $python_bin -m pip install --upgrade $install_target"
    info "Dry run: would run navin as: $python_bin -m navin"
  elif command -v uv >/dev/null 2>&1; then
    info "Dry run: would run: uv tool install --python $python_bin --force --upgrade $install_target"
    info "Dry run: would run navin as: uv tool run --from $install_target navin"
  elif command -v pipx >/dev/null 2>&1; then
    info "Dry run: would run: pipx install --python $python_bin --force $install_target"
    info "Dry run: would run navin as: pipx run --spec $install_target navin"
  else
    venv_dir="${NAVIN_VENV:-$HOME/.navin/venv}"
    info "Dry run: would create or reuse a dedicated virtual environment: $venv_dir"
    info "Dry run: would run: $venv_dir/bin/python -m pip install --upgrade $install_target"
    info "Dry run: would run navin as: $venv_dir/bin/python -m navin"
  fi
  info "Dry run: no changes made."
  exit 0
fi

if python_is_virtual_env; then
  install_with_active_python || install_failure_hint
else
  installed="0"

  if command -v uv >/dev/null 2>&1; then
    if install_with_uv; then
      installed="1"
    else
      info "uv tool install failed. Trying the next isolated install method..."
    fi
  fi

  if [ "$installed" != "1" ] && command -v pipx >/dev/null 2>&1; then
    if install_with_pipx; then
      installed="1"
    else
      info "pipx install failed. Trying the managed virtual environment..."
    fi
  fi

  if [ "$installed" != "1" ]; then
    info "Using a dedicated virtual environment to avoid system pip."
    install_with_managed_venv || install_failure_hint
  fi
fi

check_system_tools() {
  missing=""
  for tool_spec in \
    "node:npx-based MCP servers and CLIs" \
    "ffmpeg:video/audio processing" \
    "jq:JSON processing in shell workflows" \
    "rg:fast code search" \
    "sqlite3:local databases" \
    "convert:ImageMagick image conversion" \
    "pandoc:document conversion" \
    "soffice:LibreOffice Office-to-PDF"; do
    tool="${tool_spec%%:*}"
    command -v "$tool" >/dev/null 2>&1 || missing="$missing $tool"
  done

  if [ -n "$missing" ]; then
    info ""
    info "Optional system tools not found:$missing"
    info "Some skills (video, documents, dev) work better with them."
    info "Debian/Ubuntu/WSL: sudo apt-get install -y nodejs ffmpeg jq ripgrep sqlite3 imagemagick pandoc libreoffice"
  fi
}

info "Installed navin:"
run_navin --version

check_system_tools

info ""
info "Done. Start Navin with: $(navin_try_command) webui"
info "Everything is configured directly in the platform (Settings -> Providers)."
